[CLIPPER-113] Implement model active version tracking and updates
ucbrise/clipper pull request #115
Opened 2017-04-07 03:19 UTC by dcrankshaw

This PR associated a `current_model_version` with each model and makes applications specify candidate model names but not versions. Instead, the current version of a model is deployed. Model versions are automatically updated when a newer model version is deployed. I also implemented a `set_model_version` REST call in the management frontend that allows users to manually set the current model version to any version that has previously been deployed. This allows for model rollback and roll-forward.

I removed the feedback section of the selection policy and the tutorial wording still needs a little bit of work.

2017-04-07 03:20 UTC, dcrankshaw commented
Note that in order to test this with the revised tutorial, you will need to build the `query_frontend` and `management_frontend` containers locally. The ones deployed to DockerHub are from the develop branch.

2017-04-07 03:23 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/127/
Test FAILed.

2017-04-07 03:26 UTC, dcrankshaw commented
@nishadsingh1 Can you make a version of the [deploy sklearn model image](https://github.com/ucbrise/clipper/blob/develop/examples/tutorial/img/deploy_sklearn_model.png) from the tutorial for the TensorFlow model? In other words, delete the sklearn box from [this image](https://github.com/ucbrise/clipper/blob/develop/examples/tutorial/img/deploy_tf_model.png). With this new model versioning PR, the TF model _replaces_ the sklearn model and I would like to illustrate that.

Also, what did you use to make those images? Can you add whatever powerpoint/google slides file you used to the Clipper Google Drive?

2017-04-07 03:26 UTC, dcrankshaw commented
jenkins test this please

2017-04-07 03:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/128/
Test PASSed.

2017-04-10 04:08 UTC, Corey-Zumar requested changes
Tests pass and functionality seems to be mostly complete. Comments address a couple of concerns involving behavior with `deploy_model()` in conjunction with `set_model_version`. Additionally:

* Line 491 of clipper_manager.py should refer to `Clipper.deploy_model()` instead of `Clipper.add_model()`.

* What’s the intent of the “Warning” image in the tutorial_part_2 notebook? Seems unclear to me.

2017-04-10 04:08 UTC, Corey-Zumar commented on src/frontends/src/query_frontend.hpp
> +          std::unique_lock<std::mutex> l(current_model_versions_mutex_);
Do we need to hold this lock for the entire query processing and response creation procedure?

2017-04-10 04:08 UTC, Corey-Zumar commented on src/frontends/src/query_frontend.hpp
> +          std::unique_lock<std::mutex> l(current_model_versions_mutex_);
As above, do we need to hold this lock for the entire update procedure or just until the `versioned_models` map is populated? If the answer is the latter, releasing the lock earlier may avoid resource contention between the `update` and `predict` functions.

2017-04-10 04:08 UTC, Corey-Zumar commented on src/libclipper/include/clipper/redis.hpp
> +* The
Nit: check documentation formatting

2017-04-10 04:08 UTC, Corey-Zumar commented on src/libclipper/src/metrics.cpp
> +#include <algorithm>
Is this include necessary? (Maybe gcc is throwing an error where clang isn't?, etc)

2017-04-10 04:08 UTC, Corey-Zumar commented on src/libclipper/src/redis.cpp
> +      return std::stoi(*result);
Should we verify that `result` is a nonnegative integer?

2017-04-10 04:08 UTC, Corey-Zumar commented on src/libclipper/src/redis.cpp
> +  subscribe_to_keyspace_changes(REDIS_CONTAINER_DB_NUM, "", subscriber,
Nit: For clarity, defining `const std::string NO_PREFIX = "";` and using it in place of `""` is clearer.

2017-04-10 04:08 UTC, Corey-Zumar commented on management/clipper_manager.py
> +    def set_model_version(model_name, model_version, num_containers=0):
We should make this the only point through which model rollback / rollforward can be achieved. Currently, we can also call `deploy_model()` while specifying a previously-added version of a model. However, `deploy_model()` has no checks in place to ensure that the model being added is actually equivalent to the old model corresponding to the given version. Hypothetically, version x of a model can therefore change throughout time, and this seems to defeat the purpose of versioning. 

We can fix this by adding checks to `deploy_model()` that fail if a model is deployed with a previously-specified version.

2017-04-10 04:08 UTC, Corey-Zumar commented on src/management/src/management_frontend_tests.cpp
> +  ASSERT_EQ(get_current_model_version(*redis_, "m"), -1);
Wouldn't we expect `get_current_model_version()` to return `4`, corresponding to the last successful call to `add_model()` with `model4`? Is attempting to set an invalid model version supposed to change the model version to `-1`? If so, we should consistently maintain the previous version in the face of an update failure, if possible.

2017-04-10 04:08 UTC, Corey-Zumar commented on management/clipper_manager.py
> +    def set_model_version(model_name, model_version, num_containers=0):
Missing `self` in parameter list

2017-04-11 22:55 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +          std::unique_lock<std::mutex> l(current_model_versions_mutex_);
Nope. The lock is in a nested block so it will go out of scope and be released on line 171 before the prediction is made.

2017-04-11 22:55 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +          std::unique_lock<std::mutex> l(current_model_versions_mutex_);
The lock goes out of scope on line 210.

2017-04-11 22:56 UTC, dcrankshaw commented on src/libclipper/include/clipper/redis.hpp
> +* The
fixed

2017-04-11 22:58 UTC, dcrankshaw commented on src/libclipper/src/metrics.cpp
> +#include <algorithm>
`std::sort` which we use in this file is defined in `<algorithm>`. I prefer to explicitly include the header dependencies for a file as much as possible and I noticed this one was missing.

2017-04-11 23:01 UTC, dcrankshaw commented on src/libclipper/src/redis.cpp
> +      return std::stoi(*result);
Yeah good idea.

2017-04-11 23:04 UTC, dcrankshaw commented on src/libclipper/src/redis.cpp
> +  subscribe_to_keyspace_changes(REDIS_CONTAINER_DB_NUM, "", subscriber,
Hmm I actually disagree here. Defining NO_PREFIX as a constant seems like treating this as a special case. I'll define a local variable `std::string prefix = ""` in each method instead.

2017-04-11 23:06 UTC, dcrankshaw commented on management/clipper_manager.py
> +    def set_model_version(model_name, model_version, num_containers=0):
Yeah this is a really good point.

2017-04-11 23:06 UTC, dcrankshaw commented on management/clipper_manager.py
> +    def set_model_version(model_name, model_version, num_containers=0):
Fixed

2017-04-12 00:04 UTC, dcrankshaw commented on src/management/src/management_frontend_tests.cpp
> +  ASSERT_EQ(get_current_model_version(*redis_, "m"), -1);
I was adding the model directly to Redis so `set_model_version` wasn't being called. I fixed this by calling the managament frontend's `RequestHandler::add_model` with JSON and it now should reflect the expected behavior.

2017-04-12 00:45 UTC, dcrankshaw commented on management/clipper_manager.py
> +    def set_model_version(model_name, model_version, num_containers=0):
I added checks to the management frontend's `add_application` and `add_model` methods to reject duplicate adds.

2017-04-12 01:12 UTC, dcrankshaw commented
@Corey-Zumar I addressed your comments. I also added a check to prevent duplicate adding of applications or model versions. This fixes #112.

2017-04-12 01:19 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/136/
Test FAILed.

2017-04-12 01:39 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/137/
Test FAILed.

2017-04-12 10:03 UTC, Corey-Zumar approved these changes
Awesome, LGTM. Will merge after jenkins is able to build successfully.

2017-04-12 15:32 UTC, dcrankshaw commented
@Corey-Zumar BTW the warning in the tutorial is because @nishadsingh1 said he accidentally ran cleanup too early the first time he ran the tutorial. The idea was to have a visual separation from the tutorial code and the cleanup. It's been there for awhile, I just moved the location around slightly.

2017-04-12 15:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/140/
Test PASSed.

2017-04-12 15:57 UTC, dcrankshaw commented
@Corey-Zumar Hold off on merging this until the tutorial is updated. Should be sometime today.

2017-04-12 16:24 UTC, dcrankshaw commented
@Corey-Zumar Tutorial is updated. This PR is good to go once Jenkins passes it.

2017-04-12 16:34 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/141/
Test PASSed.

2017-04-12 20:03 UTC, merged