[CLIPPER-107][CLIPPER-109]
ucbrise/clipper pull request #116
Opened 2017-04-09 23:45 UTC by Corey-Zumar

Modifies query frontend and dependent infrastructure to return JSON-formatted responses to prediction queries.

From [CLIPPER-107] and the functional spec:

> The format of the response body is a JSON object with the following fields:
> 
> * Output (JSON key name “output”): The prediction JSON object.
> * Default used (JSON key name “default”): A boolean set to true if the model did not return in time and the default output was used. False otherwise.
>
> If there is a non-recoverable error during query execution, an error JSON object will be returned instead and the HTTP response code will be set to the most appropriate error code (a 400 or 500 error code). The format of the error is a JSON object with the following fields:
> * Error (JSON key name “error”): The name of the error.
> * Cause (JSON key name “cause”): A string describing the source of the error.

Note: This PR is currently based on the branch corresponding to #89. As a result, many changes from #89 are redundantly included here.

2017-04-09 23:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/129/
Test FAILed.

2017-04-10 00:04 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/130/
Test PASSed.

2017-04-11 22:06 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/133/
Test PASSed.

2017-04-11 22:12 UTC, dcrankshaw requested changes
This looks great. We should wait for #89 to be merged first.

Does this require any changes to `clipper_manager.py` or the tutorial (beyond those needed for #89)?

2017-04-11 22:12 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +const char* PREDICTION_ERROR_RESPONSE_KEY_CAUSE = "cause";
Why are these `char*` instead of `std::string`? (I'm guessing there's a good reason)

2017-04-11 22:12 UTC, dcrankshaw commented on src/libclipper/include/clipper/query_processor.hpp
>  #include <utility>
Add `#include <stdexcept>` (it's better to explicitly include all the headers needed)

2017-04-11 22:12 UTC, dcrankshaw commented on src/libclipper/include/clipper/query_processor.hpp
> +
Let's define this in a separate `exceptions.hpp` file.

2017-04-11 22:12 UTC, dcrankshaw commented on src/libclipper/src/query_processor.cpp
> +
Move to `exceptions.cpp`

2017-04-11 22:12 UTC, dcrankshaw commented on src/management/src/management_frontend.hpp
> +   "default_output" := number,
s/number/float

2017-04-11 23:35 UTC, Corey-Zumar commented on src/frontends/src/query_frontend.hpp
> +const char* PREDICTION_ERROR_RESPONSE_KEY_CAUSE = "cause";
Our utility methods for adding key-value pairs to JSON objects expect `char*` keys. There is no implicit cast from `std::string` to `char*`, so I've defined the constants this way. Alternatively, I could define these with the `std::string` type and call `.data()` to get char* pointers, but this seems less readable.

2017-04-12 10:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/138/
Test FAILed.

2017-04-12 10:18 UTC, Corey-Zumar reviewed
@dcrankshaw Addressed your comments - moved `PredictError` to separate `exceptions.hpp` and `exceptions.cpp` files.

2017-04-12 10:18 UTC, Corey-Zumar commented on src/management/src/management_frontend.hpp
> +   "default_output" := number,
Done

2017-04-12 10:19 UTC, Corey-Zumar commented on src/libclipper/include/clipper/query_processor.hpp
> +
Done

2017-04-12 10:19 UTC, Corey-Zumar commented on src/libclipper/include/clipper/query_processor.hpp
>  #include <utility>
Included `stdexept` in `exceptions.hpp`

2017-04-12 10:20 UTC, Corey-Zumar commented on src/libclipper/src/query_processor.cpp
> +
Done

2017-04-12 10:29 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/139/
Test PASSed.

2017-04-12 15:30 UTC, dcrankshaw commented
LGTM. We need to wait on #115 and then #89 before merging this though

2017-04-12 15:30 UTC, dcrankshaw approved these changes

2017-04-13 02:39 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/142/
Test PASSed.

2017-04-14 00:09 UTC, dcrankshaw commented on src/libclipper/src/query_processor.cpp
>      std::chrono::time_point<std::chrono::high_resolution_clock> end =
@Corey-Zumar Can you add a ratio counter here that tracks the fraction of predictions that use the default output?

2017-04-14 06:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/147/
Test PASSed.

2017-04-14 07:06 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/148/
Test PASSed.

2017-04-14 07:24 UTC, Corey-Zumar commented
@dcrankshaw Rebased on `develop`. Please take another look over the code and confirm that the tutorial runs properly before merging - it's working well for me.

2017-04-14 07:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/149/
Test FAILed.

2017-04-14 07:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/150/
Test FAILed.

2017-04-14 08:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/151/
Test PASSed.

2017-04-14 09:01 UTC, Corey-Zumar commented on src/libclipper/src/query_processor.cpp
>      std::chrono::time_point<std::chrono::high_resolution_clock> end =
Done

2017-04-14 09:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/152/
Test PASSed.

2017-04-17 16:32 UTC, dcrankshaw commented
LGTM. Confirming that the tutorial works for me as well.

2017-04-17 16:32 UTC, merged