[CLIPPER-117] List apps and get app info requests served by mgmtfrontend API
ucbrise/clipper pull request #119
Opened 2017-04-11 16:12 UTC by nishadsingh1

The management frontend API now has 2 new GET endpoints:
1. /get_application (returns a JSON object with full info about the requested app)
2. /get_applications (returns a list of names of all apps or, if provided `verbose`==True, a list of full JSON objects of all apps)

The returned JSON objects are in the same format that is requested by /add_application. The intent is that there will now be a uniform externally-facing app info format that is distinct from our redis storage format. See `management_frontend_tests.cpp` for examples.

Python management library now uses these endpoints. Their return types have changed slightly; they now return application objects in the same format requested by /add_application.

https://clipper.atlassian.net/browse/CLIPPER-117

2017-04-11 16:15 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-04-11 22:42 UTC, dcrankshaw commented
jenkins test this please

2017-04-11 22:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/135/
Test FAILed.

2017-04-11 23:29 UTC, Corey-Zumar requested changes
Looks good in general - noted a few minor errors and commented with requests for documentation & formatting nits. 

When you're done making changes, run `/bin/format_code.sh` in order to pass code format checks necessary for merge.

2017-04-11 23:29 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            If `verbose` == False, the list contains the apps' names.
Let's list `verbose` under a separate `Parameters` documentation header instead of `Returns`. See `register_applications()` for reference.

2017-04-11 23:29 UTC, Corey-Zumar commented on src/libclipper/include/clipper/json_util.hpp
> +rapidjson::Value& check_kv_type_is_bool_and_return(rapidjson::Value& d,
The reason for defining this method for the `bool` case is that `check_kv_type_and_return` doesn't support checking multiple types, yet we are required to match against `rapidjson::kFalseType` and `rapidjson::kTrueType` for booleans. We could consider modifying `check_kv_type_and_return` to take a vector of types, but  this solution seems fine - just throwing the idea out there.

2017-04-11 23:29 UTC, Corey-Zumar commented on src/libclipper/include/clipper/json_util.hpp
> +rapidjson::Value& get_array(rapidjson::Value& d, const char* key_name) {
This is currently unused. Is there a purpose for including it in addition to our type-specific `get_array` methods (`get_int_array`, etc)?

2017-04-11 23:29 UTC, Corey-Zumar commented on src/libclipper/include/clipper/json_util.hpp
> +void set_candidate_models_doc(std::string& candidate_models_redis_format,
We should test this method because it depends on a specific redis format that may change in the future. Consider creating a mock list of candidate models adhering to the current format as in `JsonUtilTests#TestParseCandidateModels` and invoking set_candidate_models_doc on this mock.

2017-04-11 23:29 UTC, Corey-Zumar commented on src/libclipper/include/clipper/json_util.hpp
> +void set_app_info_doc(std::unordered_map<std::string, std::string>& app_info,
Write a unit test for this method as well

2017-04-11 23:29 UTC, Corey-Zumar commented on src/libclipper/src/redis.cpp
> +  return redis_data;
Unintentional return statement? Please document this method once it's fixed or remove it if it's unnecessary.

2017-04-11 23:29 UTC, Corey-Zumar commented on src/management/src/management_frontend.hpp
>  const std::string GET_APPLICATIONS = ADMIN_PATH + "/get_applications$";
For clarity, I think we should rename `get_applications` to `get_all_applications`. This creates a more intuitive distinction between the endpoint that retrieves all applications and the endpoint that retrieves a specific application based on user-provided parameters.

2017-04-11 23:29 UTC, Corey-Zumar commented on src/management/src/management_frontend.hpp
> +   * \return Returns a JSON string that encodes a list with info about
As in `clipper_manager.py`, move `verbose` under a separate `params` documentation section

2017-04-11 23:29 UTC, Corey-Zumar commented on src/management/src/management_frontend_tests.cpp
> +  ASSERT_EQ(request_doc, response_doc);
This is fine for now. I think it's possible that in the future we will specify JSON flags for an `add_application` call that should not be returned to the user by `get_application`.

2017-04-11 23:29 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            registered with Clipper, None is returned.
This method does not return `None` if no application with name `name` is registered. Rather, invoking `get_app_info("nonexistent_name")` returns the following JSON dictionary:

```
{
  "name": "nonexistent_name"
}
```

2017-04-18 21:07 UTC, nishadsingh1 commented on src/management/src/management_frontend.hpp
> +   * \return Returns a JSON string that encodes a list with info about
Are you sure about this? The other methods in management_frontend.hpp have their desired json input schema shown in the same way that it is here.

2017-04-18 21:07 UTC, nishadsingh1 commented on src/management/src/management_frontend.hpp
>  const std::string GET_APPLICATIONS = ADMIN_PATH + "/get_applications$";
I like that :)

2017-04-18 21:08 UTC, nishadsingh1 commented on src/libclipper/src/redis.cpp
> +  return redis_data;
Thanks for the catch; the whole method is unnecessary.

2017-04-18 21:08 UTC, nishadsingh1 commented on src/libclipper/include/clipper/json_util.hpp
> +rapidjson::Value& get_array(rapidjson::Value& d, const char* key_name) {
Yep, it's unnecessary – forgot to clean it up.

2017-04-18 21:08 UTC, nishadsingh1 commented on src/libclipper/include/clipper/json_util.hpp
> +rapidjson::Value& check_kv_type_is_bool_and_return(rapidjson::Value& d,
Yep, that could also definitely work. Both of these solutions seem pretty hacky; I'll look into a cleaner fix.

2017-04-18 21:08 UTC, nishadsingh1 commented on management/clipper_manager.py
> +            registered with Clipper, None is returned.
Great, thank you for the catch; I was manually adding the name back in within the endpoint handling function without checking if redis actually returned a valid app object.

2017-04-18 21:08 UTC, nishadsingh1 commented on management/clipper_manager.py
> +            If `verbose` == False, the list contains the apps' names.
Cool, makes sense.

2017-04-19 14:39 UTC, nishadsingh1 commented
Made the recommended changes and:
- Moved function implementations out of `json_util.hpp` to `json_util.cpp`
- Renamed relevant function, most notably set_app_info_doc —> set_json_doc_from_redis_app_metadata. 
- set_json_doc_from_redis_app_metadata now makes use of several helper functions dedicated to transforming specific fields from their redis format to their publicly facing format
- Updated this transformation for the changed candidate model storage
- moved `get_all_applications` logic out of `redis.cpp`. Before, I had a function in `redis.cpp` iterating and making requests to redis. This seems like the sort of thing that shouldn’t exist in an adapter.

Added/updated the following tests:

**Management front-end tests**
TestGetApplicationCorrect
TestGetNonexistantApplicationCorrect
TestGetApplicationMalformedJson

TestGetAllApplicationsVerboseCorrect
TestGetAllApplicationsVerboseNoneRegisteredCorrect

TestGetAllApplicationsNotVerboseCorrect
TestGetAllApplicationsNotVerboseNoneRegisteredCorrect

TestGetAllApplicationsMalformedJson

**Redis tests**
ListApplicationNames
ListApplicationNamesNoneRegistered

**JSON util tests**
TestSetJsonDocFromRedisAppMetadata

Running the code formatting script made some changes in the files I touched. I included those changes here but I'm happy to remove them if the previous formatting was intentional.

2017-04-19 14:41 UTC, nishadsingh1 commented
I think that something about the way I rebased on develop and merged made this PR include a lot of changes that have already been made. I'm going to scrap it and make a new one – apologies for the confusion.

2017-04-19 14:42 UTC, closed without merging