[CLIPPER-149] Container reconnection
ucbrise/clipper pull request #121
Opened 2017-04-16 11:40 UTC by Corey-Zumar

2017-04-16 11:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/153/
Test FAILed.

2017-04-16 11:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/154/
Test FAILed.

2017-04-19 04:00 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/158/
Test FAILed.

2017-04-19 19:59 UTC, dcrankshaw commented
@Corey-Zumar Should I review this yet?

2017-04-19 21:14 UTC, Corey-Zumar commented
@dcrankshaw The code is fully functional. I just need to update the container implementation docs - will do that this evening and have the PR ready for review by tonight.

2017-04-19 21:16 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/161/
Test FAILed.

2017-04-19 21:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/162/
Test PASSed.

2017-04-19 23:46 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/163/
Test PASSed.

2017-04-20 03:46 UTC, Corey-Zumar commented
@dcrankshaw This is ready for review

2017-04-20 03:55 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/164/
Test PASSed.

2017-04-20 04:05 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/165/
Test PASSed.

2017-04-20 06:04 UTC, dcrankshaw requested changes
I reviewed the revised protocol and things generally look good. I'll go over the code in more detail tomorrow. But we should definitely have an automated test for this. It doesn't have to be a unit test (unit testing this is likely to be hard), but can you write a script that we can use to test the RPC service implementation as part of continuous integration.

Probably the easiest way to do this is to create something like the RPC benchmark that uses just the RPC system on the Clipper side of things, and then create Python and Java testing containers. The script can start the containers, then run the RPC tester twice. The RPC tester can internally check the logic of the RPC system (correct messages sent, etc) and exit with a non-zero exit code if any problems are detected. By running the RPC tester twice (or just destroying the RPC system instance and creating it again in the C++ code), you can make sure that the reconnect mechanisms work. Let me know if you have questions about testing this.

2017-04-20 06:04 UTC, dcrankshaw commented on containers/container_implementation.md
> +  * **Message Id**: A unique identifier, encoded as an unsigned integer, corresponding to the container content message. When handling a prediction request sent via a *contaner content message* from
container is mis-spelled in the second sentence

2017-04-20 06:04 UTC, dcrankshaw commented on containers/container_implementation.md
> +- Sessions are initiated and sustained by a heartbeating process. The initial detection of a two-way heartbeat between Clipper and a container marks the creation of a successful connection, and the l
Note whether the heartbeat is sent from Clipper to the container or the container to Clipper

2017-04-20 06:04 UTC, dcrankshaw commented on containers/container_implementation.md
> +
Format the python code blocks in triple backticks like the following to get Python syntax highlighting
````
```py
 # Code goes here
```
````

2017-04-20 06:04 UTC, dcrankshaw commented on containers/container_implementation.md
> +The current implementation uses the values `D = 5 seconds` and `TO = 60 seconds`.
Any objections to making the default timeout 30 seconds? I'd rather be slightly more aggressive with our defaults.

2017-04-20 06:04 UTC, dcrankshaw commented on containers/container_implementation.md
> +### For additional container lifecycle references, see:
Very nice writeup. Welcome to the darkside of RPC implementations 😛. People (i.e. me) always start out by thinking that their RPC use case is simple and they should write their own. And then the implementation inevitably needs to get more complex as they realize they need things like heartbeating.

2017-04-20 06:04 UTC, dcrankshaw commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/ModelContainer.java
> +  private static final long SOCKET_ACTIVITY_TIMEOUT_MILLIS = 60000;
Can we make these configurable at runtime?

2017-04-20 21:47 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/167/
Test PASSed.

2017-04-24 09:41 UTC, Corey-Zumar commented on containers/container_implementation.md
> +  * **Message Id**: A unique identifier, encoded as an unsigned integer, corresponding to the container content message. When handling a prediction request sent via a *contaner content message* from
Fixed

2017-04-24 09:41 UTC, Corey-Zumar commented on containers/container_implementation.md
> +
Done

2017-04-24 09:41 UTC, Corey-Zumar commented on containers/container_implementation.md
> +- Sessions are initiated and sustained by a heartbeating process. The initial detection of a two-way heartbeat between Clipper and a container marks the creation of a successful connection, and the l
Done

2017-04-24 09:41 UTC, Corey-Zumar commented on containers/container_implementation.md
> +The current implementation uses the values `D = 5 seconds` and `TO = 60 seconds`.
Sure! Done.

2017-04-24 09:41 UTC, Corey-Zumar commented on containers/container_implementation.md
> +### For additional container lifecycle references, see:
Thank you! Heartbeating definitely made things more complicated (~1000 lines later...)

2017-04-24 09:41 UTC, Corey-Zumar commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/ModelContainer.java
> +  private static final long SOCKET_ACTIVITY_TIMEOUT_MILLIS = 60000;
Runtime configuration of these parameters will create behavioral inconsistencies w.r.t RPC across container instances. I think all containers corresponding to a given language should maintain a consistent RPC protocol.

2017-04-24 09:56 UTC, Corey-Zumar commented
@dcrankshaw 

Added a comprehensive test for correct RPC functionality. You can run the test by executing the `test_container_rpc.sh` script in `containers/tests`. The test operates as follows:

1. Containers maintain a timestamped log of recent RPC messages (stored via ringbuffer). 
2. The test script launches a Java container and a Python container, each with models having access to the RPC message log
3. The test script executes the `rpctest` target, starting Clipper's `rpc_container_test`
4. Clipper waits for the containers to connect. It then requests all recent log messages from Clipper based on the system time
5. Clipper verifies that the container's log messages are consistent with correct RPC protocol, logging any errors if they occur.
6. Clipper returns exit code `0` if the containers' protocols are valid, else it returns exit code `1`.
7. The test script repeats steps 3-6.
8. The test scripts exits with code `0` if both iterations of `rpc_container_test` were successful. Otherwise, it exits with code `1`.

`rpc_container_test` will fail automatically if containers are not validated within a configurable timeout (`test_container_rpc.sh` specifies a timeout of 20 seconds).

2017-04-24 10:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/176/
Test PASSed.

2017-04-24 10:53 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/177/
Test PASSed.

2017-04-24 11:03 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/178/
Test PASSed.

2017-04-24 11:17 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/179/
Test PASSed.

2017-04-24 11:27 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/180/
Test PASSed.

2017-04-24 11:37 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/181/
Test PASSed.

2017-04-25 21:43 UTC, dcrankshaw commented
Reviewing now. Can you add your note about how the test works from the above Github comment as a comment at the top of `test_container_rpc.sh`?

2017-04-25 23:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/196/
Test PASSed.

2017-04-25 23:54 UTC, dcrankshaw commented on containers/java/clipper-java-container/pom.xml
> +      </plugin>
This just packages all the containers into a single self-container jar so you don't have to worry about a bunch of classpath entries when running it

2017-04-25 23:56 UTC, dcrankshaw commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/ModelContainer.java
> +  private final RPCEventHistory eventHistory;
What is RPCEventHistory?

2017-04-26 00:00 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/197/
Test PASSed.

2017-04-26 02:06 UTC, dcrankshaw requested changes
Overall this looks good. No major changes. Given the size of the PR there might be things that got lost in the details, but I didn't see anything.

Address my comments then I'm going to do some more testing (run the test again, make sure unit tests still pass with this new addition, make sure we didn't break the tutorial, etc). But I think we should be able to get this merged soon.

2017-04-26 02:06 UTC, dcrankshaw commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/RPCProtocolTest.java
> +// import org.junit.Test;
Sorry I forgot to remove commented out code. Remove this.

2017-04-26 02:06 UTC, dcrankshaw commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/RPCProtocolTest.java
> +  // @Test
Remove comment

2017-04-26 02:06 UTC, dcrankshaw commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/logging/RPCEventHistory.java
> +public class RPCEventHistory {
Is this just for logging?

2017-04-26 02:06 UTC, dcrankshaw commented on containers/java/clipper-java-container/src/test/java/clipper/container/app/RPCEventHistoryTest.java
> +package clipper.container.app;
Add maven tests to `./bin/run_unittests.sh`

2017-04-26 02:06 UTC, dcrankshaw commented on containers/java/clipper-java-container/src/test/java/clipper/container/app/RPCEventHistoryTest.java
> +package clipper.container.app;
Also, delete `ContainerTest.java` because we already have an example container in `src/main` and it's not really a test. It will prevent `mvn test` from terminating.

2017-04-26 02:06 UTC, dcrankshaw commented on containers/test/test_container_rpc.sh
> +# This container RPC test operates as follows:
Add a call to this script to `bin/run_unittests.sh`. Now we can test the RPC service in CI. (Don't be worried if it fails on Jenkins at first. The jenkins machines may be missing some dependencies that we need to install.

2017-04-26 02:06 UTC, dcrankshaw commented on containers/test/test_container_rpc.sh
> +./rpctest --num_containers=2 --timeout_seconds=20
This script doesn't start Redis. That's fine, because it should be called from `run_unittests.sh` which does start Redis. But it needs to take the Redis port as an argument because that script starts Redis on a random port.

Modify the calls to `rpctest` to the following:

```sh
# $1 is the first argument to the script
REDIS_PORT=$1
./rpctest --num_containers=2 --timeout_seconds=20 --redis_port $REDIS_PORT
redis-cli -p $REDIS_PORT "flushall"
echo "Sleeping for 5 seconds..."
sleep 5s
echo "Executing RPC test (second iteration)..."
./rpctest --num_containers=2 --timeout_seconds=20 --redis_port $REDIS_PORT
redis-cli -p $REDIS_PORT "flushall"
```

2017-04-26 11:15 UTC, Corey-Zumar commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/ModelContainer.java
> +  private final RPCEventHistory eventHistory;
Added class documentation. This is a circular buffer containing the most recent RPC events involving the container.

2017-04-26 11:15 UTC, Corey-Zumar commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/RPCProtocolTest.java
> +// import org.junit.Test;
Done

2017-04-26 11:15 UTC, Corey-Zumar commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/RPCProtocolTest.java
> +  // @Test
Done

2017-04-26 11:15 UTC, Corey-Zumar commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/logging/RPCEventHistory.java
> +public class RPCEventHistory {
In the sense that it's for maintaining a log of recent RPC events to be used in validation of the RPC protocol, yes. Open to different package name suggestions if something else is more descriptive/accurate

2017-04-26 11:15 UTC, Corey-Zumar commented on containers/java/clipper-java-container/src/test/java/clipper/container/app/RPCEventHistoryTest.java
> +package clipper.container.app;
Done! Also fixed the tests...

2017-04-26 11:15 UTC, Corey-Zumar commented on containers/test/test_container_rpc.sh
> +# This container RPC test operates as follows:
Done

2017-04-26 11:15 UTC, Corey-Zumar commented on containers/test/test_container_rpc.sh
> +./rpctest --num_containers=2 --timeout_seconds=20
Done! Thanks for the code

2017-04-26 11:15 UTC, Corey-Zumar commented
@dcrankshaw Addressed your comments

2017-04-26 11:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/212/
Test FAILed.

2017-04-26 14:56 UTC, dcrankshaw commented on containers/java/clipper-java-container/src/main/java/clipper/container/app/logging/RPCEventHistory.java
> +public class RPCEventHistory {
No that's fine. I just wasn't sure what the purpose of the event history was (and the RPC protocol test was one of the last files I looked at when reviewing, so I saw this file first).

2017-04-26 16:44 UTC, dcrankshaw commented
jenkins test this please

2017-04-26 16:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/220/
Test FAILed.

2017-04-26 17:22 UTC, dcrankshaw commented
jenkins test this please

2017-04-26 17:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/221/
Test FAILed.

2017-04-26 17:38 UTC, shaneknapp commented
test this please

2017-04-26 17:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/222/
Test FAILed.

2017-04-26 17:54 UTC, shaneknapp commented
test this please

2017-04-26 18:00 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/223/
Test FAILed.

2017-04-26 18:04 UTC, shaneknapp commented
ok, we're using the default system java8...  build still failing, but i've at least got that bit sorted.

2017-04-26 20:27 UTC, shaneknapp commented
test this please

2017-04-26 20:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/224/
Test FAILed.

2017-04-26 21:09 UTC, dcrankshaw commented
I think Jenkins should be able to run the tests now.

@Corey-Zumar can you update to the latest on develop and I'll do a last round of reviews before merging?

2017-04-26 21:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/226/
Test FAILed.

2017-04-26 21:30 UTC, Corey-Zumar commented
@dcrankshaw Rebased on develop

2017-04-26 21:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/228/
Test FAILed.

2017-04-26 21:51 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/230/
Test FAILed.

2017-04-26 21:51 UTC, dcrankshaw commented
jenkins test this please

2017-04-26 22:00 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/231/
Test FAILed.

2017-04-27 01:06 UTC, dcrankshaw commented
jenkins test this please

2017-04-27 01:22 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/236/
Test PASSed.

2017-04-27 01:35 UTC, dcrankshaw commented
Boom! Tests passed.

2017-04-27 01:35 UTC, dcrankshaw approved these changes

2017-04-27 01:35 UTC, merged

2017-04-27 04:31 UTC, shaneknapp commented
nice!

2017-04-27 04:33 UTC, shaneknapp commented
for reference:
1) i had to remove the jenkins-managed JDK as it would override the default system JDK (7 vs 8)
2) built jmzq and disted it to the workers w/ansible:  https://github.com/ucbrise/jenkins-infra/pull/49
3) profit