[CLIPPER-57] Read existing configuration from Redis on startup
ucbrise/clipper pull request #123
Opened 2017-04-17 22:58 UTC by giulio-zhou

* Create two functions get_all_model_names() and
  get_all_application_names() which call the KEYS command with a
  wildcard (*) argument on the model and application table
* Update query frontend to (1) add existing applications and
  (2) fill internal state with current model name and versions
  on startup

2017-04-17 23:00 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-04-19 15:28 UTC, dcrankshaw commented
jenkins test this please

2017-04-19 15:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/159/
Test FAILed.

2017-04-19 19:13 UTC, dcrankshaw requested changes
This looks good. I tested it locally and it seems to work. We should add unit tests for this though.

Add some tests to the query_frontend that first populate the application/model tables using Redis then create a new query frontend `RequestHandler` object and make sure it reads Redis correctly and adds the right models/versions and applications.

Note that when adding models you'll need explicitly set the current model version as well because the management frontend does that (https://github.com/ucbrise/clipper/blob/develop/src/management/src/management_frontend.hpp#L282-L314).

Make sure to have separate tests for models and applications.

2017-04-19 19:13 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +      // Is there a way/need to not repeat these function calls? (from above)
Repeating them is fine. There's not much duplicate code.

2017-04-19 19:13 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +      std::string policy = app_info["policy"];
This PR is based on an old commit. Update to the latest version. You'll notice that applications no longer have a policy field and now have a `default_output` field that needs to be set.

2017-04-19 19:13 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +      // Error handle model_version being < 0?
Yeah you should check for it. If it is < 0, log an error then throw a runtime exception.

2017-04-19 19:13 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +         clipper::redis::get_all_application_names(redis_connection_)) {
Can you save the vector of existing app names and log them in a useful message. Something like "Found 3 existing applications registered in Clipper: app_name_1, app_name_2, app_name_3."

2017-04-19 19:13 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +    }
After you've initialized the `current_model_versions_` map in this for loop, can you log the results similar to the existing applications log message: "Found 3 models deployed to Clipper: model_a@v4, model_b@v7, model_c@v1"

2017-04-20 01:30 UTC, giulio-zhou commented on src/frontends/src/query_frontend.hpp
> +         clipper::redis::get_all_application_names(redis_connection_)) {
Yeah, will do.

2017-04-20 23:48 UTC, giulio-zhou commented on src/frontends/src/query_frontend.hpp
> +      std::string policy = app_info["policy"];
Updated to include `default_output`.

2017-04-20 23:48 UTC, giulio-zhou commented on src/frontends/src/query_frontend.hpp
> +      // Error handle model_version being < 0?
Checked in new implementation with corresponding test.

2017-04-20 23:48 UTC, giulio-zhou commented on src/frontends/src/query_frontend.hpp
> +    }
Done.

2017-04-21 16:08 UTC, dcrankshaw commented
jenkins test this please

2017-04-21 16:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/168/
Test FAILed.

2017-04-21 20:48 UTC, dcrankshaw commented
jenkins test this please

2017-04-21 20:53 UTC, dcrankshaw approved these changes

2017-04-21 21:00 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/171/
Test PASSed.

2017-04-21 21:00 UTC, merged