[CLIPPER-115][CLIPPER-116] Get models and containers
ucbrise/clipper pull request #129
Opened 2017-04-24 18:36 UTC by dcrankshaw

2017-04-24 18:40 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/182/
Test FAILed.

2017-04-24 18:58 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/183/
Test PASSed.

2017-04-25 20:28 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/193/
Test PASSed.

2017-04-26 04:27 UTC, Corey-Zumar requested changes
Found some naming issues in clipper manager and the management frontend that should be easy to correct. Other than that and a couple formatting nits, it all looks good!

2017-04-26 04:27 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            If no modelss are registered with Clipper, an empty list is returned.
s\modelss\models

2017-04-26 04:27 UTC, Corey-Zumar commented on management/clipper_manager.py
> +        req_json = json.dumps({"name": name})
Request json is incorrect. This should conform to the schema defined in the management frontend:

```
   {
    "model_name" := string,
    "model_version" := int,
   }
```

This method should also have a `version` parameter with documentation.

2017-04-26 04:27 UTC, Corey-Zumar commented on management/clipper_manager.py
> +
Add parameter info for `model_version`, `replica_id`

2017-04-26 04:27 UTC, Corey-Zumar commented on management/clipper_manager.py
> +        name : str
s\name\model_name

2017-04-26 04:27 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            Returns a dictionary with the specified container's info.
Nit: Remove `Returns` from description

2017-04-26 04:27 UTC, Corey-Zumar commented on src/management/src/management_frontend.hpp
> +                json_error_msg(e.what(), GET_MODEL_REQUESTS_SCHEMA);
This should be `GET_CONTAINER_REQUESTS_SCHEMA`

2017-04-26 04:27 UTC, Corey-Zumar commented on src/management/src/management_frontend.hpp
> +                json_error_msg(e.what(), GET_MODEL_REQUESTS_SCHEMA);
`GET_CONTAINER_REQUESTS_SCHEMA`

2017-04-26 04:27 UTC, Corey-Zumar commented on src/libclipper/include/clipper/redis.hpp
> + * were found, then an empty vector will be returned.
Nit: s\were\are

2017-04-26 04:27 UTC, Corey-Zumar commented on src/libclipper/test/json_util_test.cpp
> +
Nit: unnecessary blank line

2017-04-26 06:52 UTC, dcrankshaw commented on management/clipper_manager.py
> +        req_json = json.dumps({"name": name})
Uggh. Good catch. Fixed.

2017-04-26 06:53 UTC, dcrankshaw commented on management/clipper_manager.py
> +        name : str
Done

2017-04-26 06:54 UTC, dcrankshaw commented on management/clipper_manager.py
> +
Done

2017-04-26 06:54 UTC, dcrankshaw commented on management/clipper_manager.py
> +            Returns a dictionary with the specified container's info.
Done

2017-04-26 06:55 UTC, dcrankshaw commented on src/management/src/management_frontend.hpp
> +                json_error_msg(e.what(), GET_MODEL_REQUESTS_SCHEMA);
Done

2017-04-26 06:56 UTC, dcrankshaw commented on src/management/src/management_frontend.hpp
> +                json_error_msg(e.what(), GET_MODEL_REQUESTS_SCHEMA);
Done

2017-04-26 06:56 UTC, dcrankshaw commented on src/libclipper/include/clipper/redis.hpp
> + * were found, then an empty vector will be returned.
Done

2017-04-26 06:56 UTC, dcrankshaw commented on src/libclipper/test/json_util_test.cpp
> +
Removed

2017-04-26 07:42 UTC, dcrankshaw commented on src/management/src/management_frontend.hpp
> +                json_error_msg(e.what(), GET_MODEL_REQUESTS_SCHEMA);
Oh. This is in GET_MODEL so this one is okay.

2017-04-26 07:42 UTC, dcrankshaw commented
@Corey-Zumar Addressed your review comments

2017-04-26 07:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/203/
Test FAILed.

2017-04-26 08:00 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/204/
Test PASSed.

2017-04-26 11:44 UTC, Corey-Zumar requested changes
One more naming error. Can approve and merge after

2017-04-26 11:44 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            "model_name": name,
This should be `"model_name": model_name,`

2017-04-26 15:13 UTC, dcrankshaw commented
@Corey-Zumar fixed naming error

2017-04-26 15:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/218/
Test PASSed.

2017-04-26 15:33 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/219/
Test PASSed.

2017-04-26 21:26 UTC, Corey-Zumar approved these changes
LGTM

2017-04-26 21:26 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/227/
Test PASSed.

2017-04-26 21:27 UTC, merged