[CLIPPER-150] Remove latency objective default from add_application
ucbrise/clipper pull request #137
Opened 2017-04-26 11:54 UTC by Corey-Zumar

When adding an application, the application-dependent latency objective is critical to the performance of the system. Users should understand the purpose and significance of the latency objective before adding an application. To this end, this PR removes the specification of a default latency objective in Clipper manager and improves documentation to aid user understanding.

2017-04-26 11:55 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/214/
Test FAILed.

2017-04-26 12:12 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/215/
Test PASSed.

2017-04-26 15:18 UTC, dcrankshaw requested changes
Good call. Added a comment to clarify the description of the field in the documentation.

2017-04-26 15:18 UTC, dcrankshaw commented on management/clipper_manager.py
> +            the optimal latnecy objective will vary depending on the application.
Latency is mis-spelled on the last line.

Can you add a note indicating that this is the processing latency between Clipper receiving a request and sending a response. It does not account for network latencies before a request is received or after a response is sent.

2017-04-26 21:34 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            the optimal latnecy objective will vary depending on the application.
Fixed typo and added note!

2017-04-26 21:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/229/
Test PASSed.

2017-04-26 21:50 UTC, dcrankshaw commented on management/clipper_manager.py
> +            the optimal latency objective will vary depending on the application.
You've got a couple more typos. s/is a good for testing/is likely a good starting value/

Rephrase and clean up the last sentence a bit:
> Starting at 40000 (40ms) is a good starting value, but the optimal latency objective will vary depending on the application.

2017-04-26 22:04 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            the optimal latency objective will vary depending on the application.
Done

2017-04-26 22:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/232/
Test PASSed.

2017-04-27 04:46 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/239/
Test PASSed.

2017-04-27 04:46 UTC, dcrankshaw approved these changes
LGTM

2017-04-27 04:47 UTC, merged