[CLIPPER-146] Bug fixes, logging improvements, documentation for python function deployment
ucbrise/clipper pull request #140
Opened 2017-04-26 22:50 UTC by nishadsingh1

Expanded python_container_conda_deps to include more packages. Specifically, it now includes those that are necessary to run through the tutorial (since many first time users will probably just use the same conda environment). This choice will decrease the container startup time in this case but is less resource-efficient when users are working with a more minimal conda environment, so I’m happy to reverse it.

Changed python_container_entry.sh so that it doesn’t break

Added some more logging for clarity and stderr/stdout flushes at appropriate points so that it’s easy to diagnose the status of a  python function container’s initialization

Added a (very basic) guide on deploying arbitrary python prediction functions. Will have to add to/edit this more.

2017-04-26 22:52 UTC, nishadsingh1 commented
Parts of the documentation assume that the changes in https://github.com/ucbrise/clipper/pull/130 make it through

2017-04-26 23:07 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/233/
Test PASSed.

2017-05-09 23:50 UTC, nishadsingh1 commented
This documentation in this PR assumes that the changes in #147 (#147 replaced #130) go through

2017-05-10 00:03 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/257/
Test PASSed.

2017-05-11 00:21 UTC, dcrankshaw requested changes
This looks great!

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python/python_container_conda_deps.txt
> +backports
How did you generate this list?

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python/python_container_entry.sh
> +/bin/bash -c "source activate container-env && exec python /container/python_container.py"
Why `exec python` and not just `python`?

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +# Python prediction function deployment
This should probably go in `containers/python`

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +The Clipper management library supports this functionality through `deploy_prediction_func`, which consumes a the function you want to deploy. All dependencies for the function must be installed with
Typo: s/consumes a the/consumes a

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +Prediction functions should take a list of inputs of and return a Python or numpy array of predictions. Internally, the function is free to do anything so long as the function's closure captures its
typo: s/list of inputs of/list of inputs

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +Prediction functions should take a list of inputs of and return a Python or numpy array of predictions. Internally, the function is free to do anything so long as the function's closure captures its
Also, specify that the function should take a list of inputs of the specified type (e.g doubles). Also, models return strings not floats. So the function should return a list of JSON strings the same length as the list of inputs, where the output at index `i` of the list is the prediction for input at index `i`.

Also add a note that any transient state (e.g. a database or network connection) will not be captured correctly.

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +      return model.predict(centered_inputs)
Wrap this code block in triple-backticks to get Python syntax highlighting:

````
```py
# code goes here...
```
````

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +      num_containers=1)
triple backticks for syntax highlighting

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +If none of your packages have conflicting dependencies, the management library will check for the existence of your packages in the linux-64 conda channel (the channel the container will use). If any
Typo: "If any such packages exist, they will be skipped..." I think you meant something like "If any your packages cannot be found..."

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +### 4. Loading your prediction function
Can you double check that 3 and 4 happen in this order? I think that we load the model before connecting to Clipper, but I could be wrong.

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +If you run into issues not listed here, please file an issue and we will attempt to find a generalizable approach to diagnosing and solving it.
Specify to file a GitHub issue

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +### Remote during container initialization
What does this section title mean? Specifically, what is remote here?

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +Calling `deploy_prediction_func` spins up a container and loads it with the necessary info to create your model. However, it may take some time before the model-container is ready to serve prediction
Specify that "some time" could be several minutes.

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +Make sure that you test your function locally before deploying it. Remember that it should take as input a list of datapoints (numpy arrays or native Python lists) with entries of type <input_type> a
typo s/shoud/should. Remind them once again that the output should be a list of strings.

2017-05-11 00:21 UTC, dcrankshaw commented on containers/python_function_deployment.md
> +If you can confirm that your function is indeed getting called, then thereare a couple of things that could prevent its prediction from getting served:
Typo s/thereare/there are

Rephrase to: "then there are a few reasons that could prevent predictions from being served"

2017-05-11 16:12 UTC, dcrankshaw commented
I'm going to combine this PR with #147 because it seems like some of the changes here necessary to fix bugs in #147

2017-05-11 17:54 UTC, dcrankshaw commented
Combined with #147

2017-05-11 17:54 UTC, closed without merging