[CLIPPER-162] [CLIPPER-163]: Check conda environment for issues in management library
ucbrise/clipper pull request #147
Opened 2017-05-09 21:59 UTC by nishadsingh1

This is a replacement for #130

`clipper_manager.deploy_prediction_function` now inspects the user's conda environment for solvability within the container's conda channel.

If the environment on the client has packages with conflicting dependencies, we now require them to resolve those issues before deploying their prediction function.

If no packages have conflicts, we check if they all exist in the linux-64 conda channel. If they do not, we warn the user that they will not be installed on the container and continue with the deployment.

Output in the latter case can be particularly long:
<img width="820" alt="screen shot 2017-05-09 at 2 53 53 pm" src="https://cloud.githubusercontent.com/assets/6938722/25874532/d84c5c30-34c7-11e7-9553-8ae951bedbd2.png">

Should limit the number of missing packages we list to some small number (say, 5) and write out the full list to a file we give the user the path to?

2017-05-09 22:02 UTC, nishadsingh1 commented on management/clipper_manager.py
> +        process.wait()
We want to make sure the environment file gets written out before we check it for problems

2017-05-09 22:14 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/256/
Test PASSed.

2017-05-10 20:15 UTC, dcrankshaw requested changes
This is almost there. With the change to how we call `check_env.py`, this does the right thing both when the environment is solvable and when it is not and displays errors in a Jupyter notebook.

Can you write the temp files (`environment.yml`, the serialized model, etc) directly to the `/tmp` directory instead of first writing them to the current directory then copying them? This will avoid polluting the user's working directory.

2017-05-10 20:15 UTC, dcrankshaw commented on management/clipper_manager.py
> +        return process.returncode == 0
For some reason Anaconda and Jupyter are doing something funky and this didn't work for me. I found a workaround. Replace the body of this function with the following:

```py
        if "CONDA_PREFIX" not in os.environ:
            print("No Anaconda environment found")
            return False
        
        root_prefix = os.environ["CONDA_PREFIX"].split("envs")[0]
        py_path = os.path.join(root_prefix, "bin", "python")
        process = subprocess.Popen(
            "{py_path} {cur_dir}/check_env.py {environment_fname} {directory} {platform}".
            format(
                py_path=py_path,
                cur_dir=cur_dir,
                environment_fname=environment_fname,
                directory=directory,
                platform=CONTAINER_CONDA_PLATFORM),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            shell=True)
        out, err = process.communicate()
        print(out)
        print(err)
        return process.returncode == 0
```

2017-05-11 15:45 UTC, dcrankshaw commented
@nishadsingh1 I know you're busy with finals right now, so I'm going to just make these last couple changes and get this merged.

2017-05-11 17:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/261/
Test FAILed.

2017-05-11 17:06 UTC, dcrankshaw commented
So I've been testing this more and it doesn't quite seem to work. First of all, the containers take a really really long time to build. Like 10 minutes. And including the additional Python dependencies in the container didn't really reduce the time to create the container. But more importantly, as the code stands I can't get the deployed container to actually make predictions. I'm digging into the issue right now.

2017-05-11 17:16 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/262/
Test FAILed.

2017-05-11 17:53 UTC, dcrankshaw commented
Okay I'm not sure what's going on. This actually seems to be working. The containers still take a really long time to build though. We should definitely look into that and see if we can shorten that somehow.

2017-05-11 17:54 UTC, dcrankshaw approved these changes

2017-05-11 18:08 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/263/
Test PASSed.

2017-05-11 18:18 UTC, merged