[CLIPPER-155] Restart containers, persistent & remote redis
ucbrise/clipper pull request #161
Opened 2017-05-19 02:23 UTC by Corey-Zumar

Adds support for automatic restarting of containers in the case of failure. Additionally, modifies Clipper manager to support specification of a remote redis server or a path for redis data persistence (if redis was started in a docker container by the manager).

2017-05-19 02:39 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/289/
Test FAILed.

2017-05-19 02:43 UTC, dcrankshaw commented
jenkins test this please

2017-05-19 03:04 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/292/
Test FAILed.

2017-05-19 03:37 UTC, dcrankshaw commented
jenkins test this please

2017-05-19 04:00 UTC, dcrankshaw requested changes
This is causing all kinds of problems for me. Turning on redis-persistence results in an unkillable docker container. I need to reset the Docker daemon in order to kill it. Did you see this?

2017-05-19 04:00 UTC, dcrankshaw commented on management/clipper_manager.py
> +            Whether or not the container was added successfully
Be explicit about when True is returned. E.g "Returns True if the container was added successfully. Otherwise returns False."

2017-05-19 04:00 UTC, dcrankshaw commented on management/clipper_manager.py
> +        on `host` at the port specified by `redis_port`.
switch the order of the args redis_ip and redis_port. It's a little more natural to have ip then port.

2017-05-19 04:00 UTC, dcrankshaw commented on management/clipper_manager.py
> +                 restart_containers=False):
Make restart_containers default to true

2017-05-19 04:00 UTC, dcrankshaw commented on management/clipper_manager.py
> +        redis will not persist data to disk.
Should the path already exist, not exist, or does it matter?

2017-05-19 05:33 UTC, Corey-Zumar commented on management/clipper_manager.py
> +                 restart_containers=False):
Done

2017-05-19 05:33 UTC, Corey-Zumar commented on management/clipper_manager.py
> +        on `host` at the port specified by `redis_port`.
Done

2017-05-19 05:33 UTC, Corey-Zumar commented on management/clipper_manager.py
> +        redis will not persist data to disk.
It doesn't matter. Added a comment to this effect.

2017-05-19 05:33 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            Whether or not the container was added successfully
Done

2017-05-19 05:34 UTC, Corey-Zumar commented
@dcrankshaw Addressed your comments. Still unable to reproduce the unkillable container issue.

2017-05-19 05:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/297/
Test FAILed.

2017-05-19 22:06 UTC, dcrankshaw commented on management/clipper_manager.py
> +        redis will not persist data to disk.
Okay so for some reason providing `/tmp` as redis_persistence_path is breaking docker. As a workaround for now, let's force the user to specify a path that doesn't already exist and verify that in the code.

2017-05-19 22:28 UTC, dcrankshaw approved these changes
LGTM. Will merge after #164 goes in and tests pass

2017-05-20 03:41 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/311/
Test PASSed.

2017-05-20 03:52 UTC, merged