[CLIPPER-122] Add get_logs function to clipper_manager and fixes container cleanup
ucbrise/clipper pull request #164
Opened 2017-05-19 04:20 UTC by dcrankshaw

I still need to do some testing with this.

2017-05-19 04:56 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/296/
Test PASSed.

2017-05-19 21:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/300/
Test FAILed.

2017-05-19 21:16 UTC, dcrankshaw commented
@Corey-Zumar This is ready for review. It's been tested on my machine. I added a call to `get_clipper_logs()` to the end of the integration test, so you should be able to test the whole thing by running `python integration-tests/light_load_all_functionality.py`

2017-05-19 22:00 UTC, Corey-Zumar requested changes
`get_clipper_logs()` works properly. Feedback concerns commented code and documentation issues

2017-05-19 22:00 UTC, Corey-Zumar commented on management/clipper_manager.py
> +        """Returns true if the provided conda environment is compatible with the container os.
This is the method description for `_conda_env_solvable`. Please replace.

2017-05-19 22:00 UTC, Corey-Zumar commented on examples/tutorial/tutorial_part_two.ipynb
> +    "clipper.stop_all()"
By making this replacement, we've rendered our "Warning" image and description irrelevant as `cleanup()` is no longer called throughout the course of the tutorial. We should probably remove the warning info.

2017-05-19 22:00 UTC, Corey-Zumar commented on management/clipper_manager.py
> +                    self._get_docker_container_id_from_image(image))
Executes a method that is commented out: `_get_docker_container_id_from_image`

2017-05-19 22:00 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            pass
Why do we pass here? If we failed to create the directory we should not continue execution. It makes sense to pass only if the command failed due to a preexisting directory.

2017-05-19 22:00 UTC, Corey-Zumar commented on management/clipper_manager.py
> +    #     for l in containers.split("\n"):
Handle commented code - other execution points depend on it

2017-05-19 22:00 UTC, Corey-Zumar commented on management/clipper_manager.py
> +    def stop_model_containers(self):
Method prototype with no body. Remove.

2017-05-19 22:00 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            # self._execute_root("docker-compose stop", warn_only=True)
Remove commented code

2017-05-19 22:00 UTC, Corey-Zumar commented on management/clipper_manager.py
> +    # def cleanup(self):
Remove commented code

2017-05-19 22:03 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/302/
Test FAILed.

2017-05-19 22:18 UTC, dcrankshaw commented on management/clipper_manager.py
> +        """Returns true if the provided conda environment is compatible with the container os.
Done

2017-05-19 22:18 UTC, dcrankshaw commented on management/clipper_manager.py
> +                    self._get_docker_container_id_from_image(image))
Removed the additional_image_names arg and this code block

2017-05-19 22:19 UTC, dcrankshaw commented on management/clipper_manager.py
> +            pass
Changed to check if directory exists first

2017-05-19 22:19 UTC, dcrankshaw commented on management/clipper_manager.py
> +    #     for l in containers.split("\n"):
Deleted and removed callers

2017-05-19 22:20 UTC, dcrankshaw commented on management/clipper_manager.py
> +            # self._execute_root("docker-compose stop", warn_only=True)
Done

2017-05-19 22:20 UTC, dcrankshaw commented on management/clipper_manager.py
> +    # def cleanup(self):
Done

2017-05-19 22:26 UTC, dcrankshaw commented
jenkins test this please

2017-05-19 22:38 UTC, Corey-Zumar requested changes

2017-05-19 22:38 UTC, Corey-Zumar commented on management/clipper_manager.py
> +            os.makedirs(directory)
this should be `os.makedirs(cur_time_logs_path)`

2017-05-19 22:49 UTC, Corey-Zumar approved these changes
LGTM

2017-05-19 23:09 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/305/
Test FAILed.

2017-05-19 23:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/306/
Test PASSed.

2017-05-19 23:50 UTC, dcrankshaw commented
jenkins test this please

2017-05-20 00:34 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/308/
Test PASSed.

2017-05-20 01:28 UTC, merged