[CLIPPER-154] Make a pip package
ucbrise/clipper pull request #165
Opened 2017-05-19 20:43 UTC by nishadsingh1

To test out the functionality of this PR:

**Create accounts on TestPyPI and PyPI:**
https://testpypi.python.org/pypi?%3Aaction=login_form
https://pypi.python.org/pypi?%3Aaction=login_form

**Create a file  ~/.pypirc with the following contents:**
```
[distutils]
index-servers =
  pypi
  testpypi

[pypi]
repository=https://pypi.python.org/pypi
username=your_username
password=your_password

[pypitest]
repository=https://testpypi.python.org/pypi
username=your_username
password=your_password
```

Because this file contains your credentials in plaintext, change its read/write permissions:
`chmod 600 ~/.pypirc`

**Upload our pip package to PyPI Testing server:**
python setup.py register -r testpypi
python setup.py sdist upload -r testpypi

**Install from PyPi Testing server:**
pip install -i https://testpypi.python.org/pypi clipper_admin

**Give it a go:**
import clipper_admin.clipper_manager as cm
clipper = cm.Clipper("localhost", "", "")
clipper.start()

**Upload our pip package to real PyPi server:**
python setup.py register -r pypi
python setup.py sdist upload -r pypi

**Install from real PyPi server:**
pip uninstall clipper_admin (to get rid of the one from the testing server)
pip install clipper_admin

https://clipper.atlassian.net/projects/CLIPPER/issues/CLIPPER-154

2017-05-19 20:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/298/
Test FAILed.

2017-05-19 21:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/299/
Test FAILed.

2017-05-19 21:11 UTC, nishadsingh1 commented on setup.py
> +  install_requires = ['requests', 'pyparsing', 'appdirs', 'pprint', 'subprocess32', 'sklearn', 'numpy', 'scipy', 'fabric', 'conda', 'pyyaml']
My code formatting script is hanging for some reason -- figured it was best to push this change up early and figure out the formatting issue while it's getting reviewed.

2017-05-19 21:12 UTC, dcrankshaw commented on setup.py
> +  install_requires = ['requests', 'pyparsing', 'appdirs', 'pprint', 'subprocess32', 'sklearn', 'numpy', 'scipy', 'fabric', 'conda', 'pyyaml']
Sounds good. I can format it in a sec.

2017-05-19 21:18 UTC, dcrankshaw commented
Okay just formatted the code

2017-05-19 21:34 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/301/
Test FAILed.

2017-05-19 21:46 UTC, dcrankshaw commented
jenkins test this please

2017-05-20 01:05 UTC, dcrankshaw commented
jenkins test this please

2017-05-20 01:21 UTC, dcrankshaw requested changes
Looks good. I need to do some testing, but here's a first round of comments.

2017-05-20 01:21 UTC, dcrankshaw commented on containers/python/PythonContainerDockerfile
> +COPY ../../clipper_admin/pywrencloudpickle.py python_container_conda_deps.txt /lib/
This won't work. All the paths copied into the container need to be in the directory tree whose root is the directory containing the Dockerfile (https://docs.docker.com/engine/reference/commandline/build/#build-with-path). This is also important to make sure that the automated builds on Docker hub work. Probably the easiest thing to do is to move all the container dockerfiles to the top level of the directory. You'll need to modify the paths in the Dockerfiles, as well as the script that builds all the files.

2017-05-20 01:21 UTC, dcrankshaw commented on examples/tutorial/tutorial_part_one.ipynb
> +    "sys.path.append(os.path.abspath('../../clipper_admin/'))\n",
Do you think we should import the module directly like this or make them install the pip package?

2017-05-20 01:21 UTC, dcrankshaw commented on examples/tutorial/tutorial_part_two.ipynb
> +    "sys.path.append(os.path.abspath('../../clipper_admin/'))\n",
Same question about direct import vs make them install the pip package

2017-05-20 01:21 UTC, dcrankshaw commented on setup.py
> +    description='A low latency online prediction serving system',
Make the description "Admin commands for the Clipper prediction-serving system."

2017-05-20 01:21 UTC, dcrankshaw commented on setup.py
> +    author_email='dcrankshaw@berkeley.edu',
Use `crankshaw@cs.berkeley.edu` for my email

2017-05-20 01:21 UTC, dcrankshaw commented on setup.py
> +    url='https://github.com/ucbrise/clipper',
Make the url `http://clipper.ai`

2017-05-20 01:21 UTC, dcrankshaw commented on setup.py
> +    keywords=['prediction', 'model', 'management'],
add `clipper` as a keyword

2017-05-20 01:32 UTC, nishadsingh1 commented on examples/tutorial/tutorial_part_one.ipynb
> +    "sys.path.append(os.path.abspath('../../clipper_admin/'))\n",
It does seem cleaner to make them install the pip package, especially since the intended tutorial user is a Clipper user, not developer.

2017-05-20 03:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/310/
Test FAILed.

2017-05-20 06:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/317/
Test FAILed.

2017-05-20 06:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/318/
Test FAILed.

2017-05-20 16:27 UTC, dcrankshaw requested changes
Can you update [`examples/tutorial/requirements.txt`](https://github.com/ucbrise/clipper/blob/develop/examples/tutorial/requirements.txt) to reflect the new set of Python dependencies that include the `clipper-admin` package?

2017-05-20 16:27 UTC, dcrankshaw commented on containers/python/build_container_images.sh
> +time docker build -t clipper/tf_cifar_container -f ../../TensorFlowCifarDockerfile ../../
Let's consolidate this script into `bin/build_docker_images.sh`

2017-05-20 17:07 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/319/
Test FAILed.

2017-05-20 18:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/320/
Test PASSed.

2017-05-22 17:06 UTC, dcrankshaw commented
Tested with `pip install --extra-index-url https://testpypi.python.org/pypi clipper_admin` and it works great. LGTM. Will merge once tests pass. This will break our container builds on docker hub so I'll need to update those as well.

2017-05-22 17:06 UTC, dcrankshaw approved these changes

2017-05-22 17:27 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/326/
Test PASSed.

2017-05-22 19:52 UTC, merged