Change restart policy to always for all model containers
ucbrise/clipper pull request #171
Opened 2017-05-20 07:46 UTC by rmdort

Currently clipper containers restarts on reboot, but model containers don't.

2017-05-20 07:50 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-05-20 20:38 UTC, Corey-Zumar requested changes
Thanks for catching this! Can you check the value of the `restart_containers` parameter specified in the initialization of Clipper manager and only append the flag in the add container command if `restart_containers=True`?

2017-05-21 00:31 UTC, dcrankshaw commented
jenkins ok to test

2017-05-21 00:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/323/
Test PASSed.

2017-05-21 01:00 UTC, Corey-Zumar approved these changes
LGTM

2017-05-21 01:00 UTC, merged