Python3 issue in clipper_manager.deploy_predict_function
ucbrise/clipper pull request #183
Opened 2017-05-26 17:25 UTC by jegonzal

If user's default python environment is python3 then the scrip to check conda dependencies will fail.  

This PR addresses the issue by casting strings to UTF8 bytes.

2017-05-26 17:30 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-05-26 17:30 UTC, shaneknapp commented
add to whitelist

2017-05-26 17:57 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/333/
Test PASSed.

2017-05-30 17:12 UTC, dcrankshaw requested changes
Unfortunately this change is incompatible with python2. Fortunately, there's actually an easier solution: don't open the file as a binary file.

2017-05-30 17:12 UTC, dcrankshaw commented on clipper_admin/check_and_write_deps.py
>      with open(conda_dep_abs_path, 'wb') as f:
Revert your changes and change the `open()` call to not open the file as a binary file:

```py
with open(conda_dep_abs_path, 'w') as f:
```

2017-05-30 17:12 UTC, dcrankshaw commented on clipper_admin/check_and_write_deps.py
>      with open(pip_dep_abs_path, 'wb') as f:
Change this `open()` call in the same way:

```py
with open(pip_dep_abs_path, 'wb') as f:
```

2017-05-30 17:22 UTC, dcrankshaw requested changes
Remove extraneous kw-arg

2017-05-30 17:22 UTC, dcrankshaw commented on clipper_admin/check_and_write_deps.py
> +            f.write("%s\n" % '='.join(item.split()), encoding="UTF8")
Remove the `encoding="UTF8"` keyword-arg

2017-05-30 17:22 UTC, dcrankshaw commented on clipper_admin/check_and_write_deps.py
> +            f.write("%s\n" % item, encoding="UTF8")
Remove the `encoding="UTF8"` keyword-arg

2017-05-30 17:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/342/
Test PASSed.

2017-05-30 20:09 UTC, dcrankshaw approved these changes
lgtm

2017-05-30 20:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/343/
Test PASSed.

2017-05-30 20:32 UTC, merged