Can deploy predict func out of anaconda env
ucbrise/clipper pull request #194
Opened 2017-06-02 09:36 UTC by nishadsingh1

Addresses issue #190

There's a ipython notebook with testcases. I think these could eventually be moved into python integration tests -- let me know what the best way to do this is would be (they require checking logs, waiting, etc).

We'd need to update this documentation when this PR goes through: https://github.com/ucbrise/clipper-website/pull/2

2017-06-02 09:40 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/357/
Test FAILed.

2017-06-02 16:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/360/
Test FAILed.

2017-06-02 16:37 UTC, nishadsingh1 commented
Jenkins failures relate to formatting; I'm still running into the problem of the hanging formatting script. I'll figure it out since it'll be needed a lot, but the code itself should be readable for review regardless

2017-06-02 17:21 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/363/
Test PASSed.

2017-06-03 00:51 UTC, dcrankshaw requested changes
This is failing for me with an ImportError: `No module named clipper_admin.pywrencloudpickle`

Also, can you print out the import error here: https://github.com/ucbrise/clipper/blob/develop/containers/python/python_container.py#L121

Something like:

```py
except ImportError as e:
    print("ImportError: %s" % e)
    sys.exit(IMPORT_ERROR_RETURN_CODE)
```

2017-06-03 00:51 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +            print("Anaconda environment was either not found or failed being exported")
Rephrase to `print("Anaconda environment was either not found or exporting the environment failed.")`

2017-06-03 00:51 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +            )
Rephrase to:
"Your function will still be serialized deployed, but may fail due to missing dependencies. In this case, please re-run inside an Anaconda environment. See http://clipper.ai/documentation/python_model_deployment/ for more information."

2017-06-03 00:51 UTC, dcrankshaw commented on containers/python/python_container_entry.sh
> +	echo "Attempting to run Python container without installing without supplied dependencies."
Rephrase/fix typo: "First attempting to run Python container without installing supplied dependencies."

2017-06-03 00:51 UTC, dcrankshaw commented on containers/python/python_container_entry.sh
> +echo "Encountered error not related to missing packages. Please refer to the above logs to diagnose."
rephrase: "Encountered error not related to missing packages. Please refer to the container logs to diagnose."

2017-06-03 17:21 UTC, dcrankshaw commented
I did a bit of cleanup to make sure that this will work when the user installed `clipper_admin` via pip. It seems to be working on my computer. I want to wait for #187 to get merged and add tests for `deploy_predict_function` then this should be good to go.

2017-06-03 17:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/371/
Test FAILed.

2017-06-03 17:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/372/
Test FAILed.

2017-06-03 17:35 UTC, dcrankshaw commented
Note that these jenkins tests were intentionally killed by me.

2017-06-03 18:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/376/
Test PASSed.

2017-06-03 18:50 UTC, dcrankshaw approved these changes
LGTM

2017-06-03 18:50 UTC, merged