Adds support for deploying PySpark models
ucbrise/clipper pull request #196
Opened 2017-06-04 01:52 UTC by dcrankshaw

You can see how it works by looking at the integration tests I added in `integration-tests/`.

This should wait for #192 before being merged.

Note that after this gets merged, we need to create an automated build for `clipper/pyspark-container` on DockerHub.

2017-06-04 02:08 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/382/
Test FAILed.

2017-06-04 02:12 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/383/
Test FAILed.

2017-06-04 02:14 UTC, dcrankshaw commented
jenkins test this please

2017-06-04 02:24 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/384/
Test FAILed.

2017-06-04 02:55 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/385/
Test FAILed.

2017-06-04 03:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/386/
Test FAILed.

2017-06-04 05:20 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/387/
Test FAILed.

2017-06-04 05:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/388/
Test FAILed.

2017-06-04 20:41 UTC, feynmanliang commented on bin/run_unittests.sh
> +    curl -o spark.tgz https://d3kbcqa49mib13.cloudfront.net/spark-2.1.1-bin-hadoop2.7.tgz
should we pull vars for these versions?

2017-06-04 20:42 UTC, feynmanliang commented on integration-tests/deploy_pyspark_models.py
> +from pyspark import SparkConf, SparkContext
Is `SparkConf` used?

2017-06-04 20:42 UTC, feynmanliang commented on containers/python/pyspark_container.py
> +from pyspark import SparkConf, SparkContext
Ditto, is `SparkConf` used?

2017-06-04 20:50 UTC, feynmanliang commented on PySparkContainerDockerfile
> +      && cd / && tar zxf /spark.tgz && mv /spark-2.1.1-bin-hadoop2.7 /spark \
Should we extract vars for these versions and `envsubst` them in?

2017-06-05 02:13 UTC, Corey-Zumar requested changes
Preliminary style review + questions. Will attempt to train and deploy PySpark models after #192 is merged and we rebase on develop.

2017-06-05 02:13 UTC, Corey-Zumar commented on clipper_admin/clipper_manager.py
> +                    # self._copytree(local_path, remote_path)
Remove commented code

2017-06-05 02:13 UTC, Corey-Zumar commented on clipper_admin/clipper_manager.py
> -    def _copytree(self, src, dst, symlinks=False, ignore=None):
What is the rationale behind deleting this method? Did you run into an issue with it?

2017-06-05 02:13 UTC, Corey-Zumar commented on clipper_admin/clipper_manager.py
> +                "failed. Your function will still be serialized deployed, but may fail due to "
I think the second sentence should read `Your function will still be serialized and deployed, but may fail due to...` (missing and)

2017-06-05 02:13 UTC, Corey-Zumar commented on clipper_admin/clipper_manager.py
> +        return deploy_result
Add a `Returns` section to documentation with type and explanation of `deploy_result`

2017-06-05 02:13 UTC, Corey-Zumar commented on clipper_admin/clipper_manager.py
>      def deploy_predict_function(self,
This method should also have `Returns` documentation

2017-06-05 02:13 UTC, Corey-Zumar commented on containers/python/pyspark_container.py
> +        if self.input_type != rpc.INPUT_TYPE_INTS:
Why are we performing an additional check on the validity of the input type? Lines 270-278 of `rpc.py` should take care of this validation.

2017-06-05 02:13 UTC, Corey-Zumar commented on containers/python/pyspark_container.py
> +    def _log_incorrect_input_type(self, input_type):
Remove this if input type validation is redundant (see comment above regarding preexisting validation in `rpc.py`)

2017-06-05 02:13 UTC, Corey-Zumar commented on integration-tests/deploy_pyspark_models.py
> +def find_unbound_port():
This doesn't have to be done now, but we should eventually create a reusable module that we can import this functionality from because it's also defined in `many_apps_many_models.py` in the same directory.

2017-06-05 02:13 UTC, Corey-Zumar commented on integration-tests/deploy_pyspark_models.py
> +    # return LabeledPoint(obj(int(fields[0]), pos_label), [float(v)/255.0 for v in fields[1:]])
Remove commented code.

2017-06-05 02:13 UTC, Corey-Zumar commented on clipper_admin/clipper_manager.py
> +            print("Vol is: %s" % vol)
Consider removing debug print statement.

2017-06-05 02:23 UTC, dcrankshaw commented on integration-tests/deploy_pyspark_models.py
> +from pyspark import SparkConf, SparkContext
removed

2017-06-05 02:23 UTC, dcrankshaw commented on containers/python/pyspark_container.py
> +from pyspark import SparkConf, SparkContext
removed

2017-06-05 02:25 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> -    def _copytree(self, src, dst, symlinks=False, ignore=None):
Yeah it wasn't working for recursive copying of directories.

2017-06-05 02:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/397/
Test FAILed.

2017-06-05 02:26 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +            print("Vol is: %s" % vol)
done

2017-06-05 02:26 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +                    # self._copytree(local_path, remote_path)
done

2017-06-05 02:26 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +                "failed. Your function will still be serialized deployed, but may fail due to "
Ahh good

2017-06-05 02:27 UTC, dcrankshaw commented
jenkins test this please

2017-06-05 02:29 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +        return deploy_result
Done

2017-06-05 02:29 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
>      def deploy_predict_function(self,
Done

2017-06-05 02:31 UTC, dcrankshaw commented on containers/python/pyspark_container.py
> +        if self.input_type != rpc.INPUT_TYPE_INTS:
Oh I copied this code from the `python_container.py` code. I didn't realize it was redundant. I'll remove it.

2017-06-05 02:35 UTC, Corey-Zumar commented on containers/python/pyspark_container.py
> +        if self.input_type != rpc.INPUT_TYPE_INTS:
Got it. Can you remove these checks from `python_container` as well?

2017-06-05 02:36 UTC, dcrankshaw commented on integration-tests/deploy_pyspark_models.py
> +def find_unbound_port():
Agreed. Filed #201.

2017-06-05 02:37 UTC, dcrankshaw commented on integration-tests/deploy_pyspark_models.py
> +    # return LabeledPoint(obj(int(fields[0]), pos_label), [float(v)/255.0 for v in fields[1:]])
Done

2017-06-05 02:38 UTC, dcrankshaw commented on containers/python/pyspark_container.py
> +        if self.input_type != rpc.INPUT_TYPE_INTS:
Yeah done

2017-06-05 02:49 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/398/
Test FAILed.

2017-06-05 02:54 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/399/
Test FAILed.

2017-06-05 03:11 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/400/
Test FAILed.

2017-06-05 03:34 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/401/
Test FAILed.

2017-06-05 04:09 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/402/
Test PASSed.

2017-06-05 05:22 UTC, Corey-Zumar requested changes
Just a couple minor comments. This works well!

2017-06-05 05:22 UTC, Corey-Zumar commented on containers/python/pyspark_container.py
> +            This model-container was configured accept data for input type {correct_input_type}"
Nit: Missing "to". This should be

`Attempted to use prediction function for input type {incorrect_input_type}, but this model-container was configured to accept data for input type {correct_input_type}`

2017-06-05 05:22 UTC, Corey-Zumar commented on PySparkContainerDockerfile
> +# vim: set filetype=dockerfile:
Remove commented code

2017-06-05 05:31 UTC, dcrankshaw commented on PySparkContainerDockerfile
> +# vim: set filetype=dockerfile:
This actually isn't a comment, it's a vim modeline directive http://vim.wikia.com/wiki/Modeline_magic

2017-06-05 06:12 UTC, Corey-Zumar approved these changes
LGTM

2017-06-05 06:12 UTC, merged