Base64 decoding for JSON byte data
ucbrise/clipper pull request #214
Opened 2017-06-15 21:06 UTC by Corey-Zumar

2017-06-15 21:12 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/435/
Test FAILed.

2017-06-15 21:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/436/
Test FAILed.

2017-06-15 21:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/437/
Test FAILed.

2017-06-15 22:28 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/438/
Test PASSed.

2017-06-16 17:09 UTC, dcrankshaw requested changes
Looks good. Minor comments.

2017-06-16 17:09 UTC, dcrankshaw commented on .gitmodules
> +[submodule "src/libs/base64"]
Since this is a header-only library, instead of adding it as a submodule, can you just copy the header into src/libcs/base64.

Also, since the library already has tests, it would be good to port them to our testing infrastructure as well. I took a quick look at them, and it doesn't look like it will be too hard.

2017-06-16 17:09 UTC, dcrankshaw commented on src/libclipper/src/json_util.cpp
> +      decoded_string.data(), decoded_string.data() + decoded_string.length());
What is the second argument here `decoded_string.data() + decoded_string.length()` for?

2017-06-16 17:09 UTC, dcrankshaw commented on src/libclipper/src/json_util.cpp
> -      throw std::invalid_argument("Base64 encoded bytes are not supported yet");
👍

2017-06-16 23:15 UTC, Corey-Zumar reviewed
@dcrankshaw Addressed your comments

2017-06-16 23:15 UTC, Corey-Zumar commented on src/libclipper/src/json_util.cpp
> +      decoded_string.data(), decoded_string.data() + decoded_string.length());
This was the second argument of the range constructor, specifying the pointer to the end of the memory to be allocated to the vector. It's cleaner to use `decoded_string.begin()` and `decoded_string.end()` instead - made that change.

2017-06-16 23:15 UTC, Corey-Zumar commented on .gitmodules
> +[submodule "src/libs/base64"]
Yep, removed the submodule and just copied the header. Ported the tests to `base64_tests.cpp`.

2017-06-16 23:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/448/
Test FAILed.

2017-06-19 16:20 UTC, dcrankshaw commented
jenkins test this please

2017-06-19 16:24 UTC, dcrankshaw commented
LGTM. Waiting for the tests to pass.

2017-06-19 16:51 UTC, dcrankshaw approved these changes

2017-06-19 16:53 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/451/
Test PASSed.

2017-06-19 23:19 UTC, merged