One-line app registration and model deployment
ucbrise/clipper pull request #223
Opened 2017-06-20 00:19 UTC by nishadsingh1

Addresses the third checkbox in #218

2017-06-20 00:20 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/455/
Test FAILed.

2017-06-20 00:40 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/456/
Test FAILed.

2017-06-20 01:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/457/
Test PASSed.

2017-06-22 18:32 UTC, dcrankshaw requested changes
So now that I'm looking at the code, these method signatures still look really complicated. These are basically convenience methods to make things simpler. If the user wants more control, she can call `register_application` and deploy_*` separately.

To simplify the method signatures:
1. Make the model name and app name the same and just have a single name parameter
2. Remove the method for `register_app_and_deploy_model`, just have it for python functions and pyspark models
3. Make the model version arg have a default argument of 1 (`model_version=1`)
4. Make slo_micros default to 100000
5. Make `input_type` the last non-default arg (so the order is name, predict_function, [pyspark model and spark context if deploy_pyspark method], input_type, default args)

2017-06-22 18:32 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +            The response object for the app registration request
What is a response object?

2017-06-22 18:32 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +        if response.status_code != 200:
Don't check for 200, use `if r.status_code == requests.codes.ok:`

2017-06-22 18:32 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +    def register_app_and_deploy_model(self,
These are really really long method names.

2017-06-22 20:53 UTC, nishadsingh1 commented
Makes sense -- do we want to give `default_output` a default as well? Maybe "-1.0" or something?

2017-06-22 21:55 UTC, nishadsingh1 commented
Didn't make the change to have a default `default_output` -- happy to add it in. The new function names `activate_predict_function` and `activate_pyspark_model` still don't seem quite right...let me know if better names come to mind.

2017-06-22 22:19 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/466/
Test PASSed.

2017-06-22 22:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/467/
Test PASSed.

2017-06-23 18:06 UTC, dcrankshaw requested changes
Mostly there. Just some naming and doc cleanup.

2017-06-23 18:06 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +DEFAULT_SLO_MICROS = 10000
This is 10 ms, make it 100 ms (100000)

2017-06-23 18:06 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +            Returns true iff the app reigstration request was successful
typo in "registration"

2017-06-23 18:06 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +    def activate_predict_function(self,
Activate isn't really the right verb. I can't think of a good shorter name that doesn't conflict with our existing API, so maybe just use the long names from before.

2017-06-23 18:06 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +                                  default_output,
Make the default output "None"

2017-06-23 18:06 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +                               default_output,
Make the default output "None"

2017-06-23 18:06 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +        predict_function : function
Don't say "refer to documentation in ..." That is really confusing and leads to hard to read docs. Just copy the text.

As we refactor this documentation, we'll create some module-level documentation about deploying models and the meaning of these fields.

2017-06-23 18:06 UTC, dcrankshaw commented on clipper_admin/clipper_manager.py
> +        predict_function : function
Fix docs (remove "refer to...")

2017-06-23 21:40 UTC, dcrankshaw commented
LGTM. Merge with develop (looks like you'll need to do that locally) and I'll do a last pass and get this merged.

2017-06-23 21:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/473/
Test PASSed.

2017-06-23 22:08 UTC, dcrankshaw approved these changes

2017-06-23 22:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/475/
Test PASSed.

2017-06-23 22:32 UTC, merged