Build new docker images in build_model with in-memory Dockerfile
ucbrise/clipper pull request #280
Opened 2017-09-01 16:57 UTC by dcrankshaw

Removes the need to write a Dockerfile to disk in the user's file system by creating an in-memory Dockefile with StringIO then adding it directly to a temporary tar file to be used as the Docker build context.

The end result is that we don't write (and potentially overwrite) Dockerfile's in the user's system.

2017-09-01 17:40 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/681/
Test FAILed.

2017-09-01 18:05 UTC, dcrankshaw commented
jenkins test this please

2017-09-01 18:43 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/683/
Test FAILed.

2017-09-01 19:27 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/684/
Test PASSed.

2017-09-01 20:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/685/
Test FAILed.

2017-09-01 20:51 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/686/
Test PASSed.

2017-09-02 06:30 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/689/
Test PASSed.

2017-09-02 22:26 UTC, Corey-Zumar requested changes
Looks good! Part two of the tutorial needs to be updated to remove the `force` argument from `build_and_deploy_model`. Once that's done, I'll merge.

2017-09-02 22:39 UTC, dcrankshaw commented
Good catch. Fixed.

On Sat, Sep 2, 2017 at 3:26 PM, Corey Zumar <notifications@github.com>
wrote:

> *@Corey-Zumar* requested changes on this pull request.
>
> Looks good! Part two of the tutorial needs to be updated to remove the
> force argument from build_and_deploy_model. Once that's done, I'll merge.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ucbrise/clipper/pull/280#pullrequestreview-60284667>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAaV5NGqTta0wAV8FCnoLedlp2sWTl1dks5sedYYgaJpZM4PKZet>
> .
>

2017-09-02 22:43 UTC, Corey-Zumar approved these changes
LGTM

2017-09-02 23:12 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/693/
Test PASSed.

2017-09-02 23:27 UTC, merged