An example of querying with an image
ucbrise/clipper pull request #326
Opened 2017-11-28 09:41 UTC by kakru

As discussed [here](https://github.com/ucbrise/clipper/issues/325).
Should go together with the [website PR](https://github.com/ucbrise/clipper-website/pull/11)

2017-11-28 09:45 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-11-29 17:31 UTC, dcrankshaw commented
jenkins ok to test

2017-11-29 18:31 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/797/
Test FAILed.

2017-11-29 21:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/798/
Test FAILed.

2017-12-01 08:23 UTC, kakru commented
Can one of the admins restart the Jenkins build - test FAIL was not related to the changes introduced in this PR

2017-12-11 18:02 UTC, dcrankshaw commented
jenkins test this please

2017-12-11 20:26 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/809/
Test PASSed.

2018-01-09 02:50 UTC, Corey-Zumar requested changes
@kakru This works really well! Just a few minor comments

2018-01-09 02:50 UTC, Corey-Zumar commented on examples/image_query/example_client.py
> +    import base64,
Remove trailing comma

2018-01-09 02:50 UTC, Corey-Zumar commented on examples/image_query/example_client.py
> +        if len(sys.argv) > 1:
Can you use [argparse](https://docs.python.org/3/library/argparse.html) here instead of parsing system arguments directly?

2018-01-09 02:50 UTC, Corey-Zumar commented on examples/image_query/README.md
> +# Running the example query
Keep only the second instruction. The rest are outdated.

2018-01-09 03:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/837/
Test PASSed.

2018-05-31 19:22 UTC, closed without merging