fixed path for model
ucbrise/clipper pull request #353
Opened 2018-01-10 19:20 UTC by bdod6

2018-01-10 19:25 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-01-10 21:09 UTC, dcrankshaw commented
jenkins test this please

2018-01-10 21:12 UTC, dcrankshaw requested changes
Thanks for doing this. Just a minor change.

2018-01-10 21:12 UTC, dcrankshaw commented on clipper_admin/clipper_admin/deployers/tensorflow.py
> +                    tf_sess_or_saved_model_path + "/*.data*"):
Instead of doing string concatenation, can you use `os.path.join` (e.g `os.path.join(tf_sess_or_saved_model_path, *.meta")`)

2018-01-10 21:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/848/
Test FAILed.

2018-01-10 21:54 UTC, dcrankshaw commented
The test failed because your Python code isn't formatted correctly. Run `./bin/format_code.sh` to format.

2018-01-10 23:26 UTC, bdod6 commented
thanks. i updated to os.path.join. I tried running your shell script but it errored out. so i just formatted it look like the way you had it before.

2018-01-10 23:43 UTC, simon-mo commented
If the error is yapf not found. That is caused by you didn’t clone the yapf submodule. You can go to $CLIPPER_ROOT/bin/ and `git clone https://github.com/google/yapf`

2018-01-24 18:37 UTC, dcrankshaw commented
jenkins test this please

2018-01-24 18:52 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/905/
Test FAILed.

2018-01-25 23:56 UTC, dcrankshaw commented
jenkins ok to test

2018-01-26 00:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/907/
Test FAILed.

2018-01-26 00:13 UTC, dcrankshaw commented
jenkins test this please

2018-01-26 00:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/908/
Test FAILed.

2018-01-26 02:27 UTC, dcrankshaw commented
jenkins test this please

2018-01-26 03:18 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/909/
Test FAILed.

2018-01-31 00:42 UTC, dcrankshaw commented
There appears to be a bug in this code. @bdod6 can you take a look at the error: https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/909/console

2018-04-04 15:41 UTC, dcrankshaw commented
Closing due to lack of activity

2018-04-04 15:41 UTC, closed without merging