Integration test for fixed-batch-size model deployment
ucbrise/clipper pull request #370
Opened 2018-01-22 06:21 UTC by Corey-Zumar

* Adds the `batch_size` parameter to relevant deployer APIs

* Fixes #365

2018-01-22 06:51 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/875/
Test FAILed.

2018-01-22 06:58 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/876/
Test FAILed.

2018-01-22 07:04 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/877/
Test FAILed.

2018-01-22 08:16 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/878/
Test FAILed.

2018-01-22 20:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/881/
Test FAILed.

2018-01-23 02:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/886/
Test FAILed.

2018-01-23 05:01 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/887/
Test FAILed.

2018-01-23 05:51 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/888/
Test FAILed.

2018-01-23 08:53 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/890/
Test PASSed.

2018-01-24 06:28 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/903/
Test PASSed.

2018-01-24 17:42 UTC, dcrankshaw requested changes
Just fix the batch size documentation and this is good to go.

2018-01-24 17:42 UTC, dcrankshaw commented on clipper_admin/clipper_admin/deployers/pyspark.py
> +        The user-defined batch size.
Can you briefly explain what batching this refers to?

2018-01-24 19:48 UTC, Corey-Zumar commented on clipper_admin/clipper_admin/deployers/pyspark.py
> +        The user-defined batch size.
Done!

2018-01-24 19:59 UTC, dcrankshaw approved these changes
LGTM

2018-01-24 20:47 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/906/
Test PASSed.

2018-01-25 00:05 UTC, merged