[WIP] Performance improvements: RPC, Data management, hashing
ucbrise/clipper pull request #393
Opened 2018-02-01 08:35 UTC by Corey-Zumar

* TODO: Fix tests, write additional tests for the serialization protocol

Fixes #334, #330, #331

2018-02-01 08:40 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/934/
Test FAILed.

2018-02-05 03:51 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/944/
Test FAILed.

2018-02-08 02:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/973/
Test FAILed.

2018-02-08 02:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/974/
Test FAILed.

2018-02-08 21:00 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/983/
Test FAILed.

2018-02-09 04:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/984/
Test FAILed.

2018-02-10 11:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/988/
Test FAILed.

2018-02-10 23:20 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/989/
Test FAILed.

2018-02-12 08:08 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/992/
Test FAILed.

2018-02-12 08:09 UTC, Corey-Zumar commented
jenkins test this please

2018-02-12 08:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/993/
Test FAILed.

2018-02-13 03:13 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/999/
Test PASSed.

2018-02-13 04:07 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1000/
Test PASSed.

2018-02-13 21:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1003/
Test FAILed.

2018-02-13 22:00 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1004/
Test FAILed.

2018-02-13 22:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1005/
Test FAILed.

2018-02-13 22:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1006/
Test FAILed.

2018-02-13 23:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1007/
Test FAILed.

2018-02-14 00:03 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1008/
Test FAILed.

2018-02-14 23:12 UTC, Corey-Zumar commented
jenkins test this please

2018-02-14 23:34 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1010/
Test FAILed.

2018-02-15 07:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1013/
Test FAILed.

2018-03-14 01:31 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1107/
Test FAILed.

2018-03-14 02:31 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1108/
Test FAILed.

2018-03-16 23:46 UTC, dcrankshaw requested changes
This looks great. I just had a few minor comments and questions.

2018-03-16 23:46 UTC, dcrankshaw commented on containers/R/rclipper_serve/src/container_rpc.hpp
> +constexpr uint32_t RPC_VERSION = 3;
Why are we starting with version 3? Why not version 1?

2018-03-16 23:46 UTC, dcrankshaw commented on containers/container_implementation.md
> +All inbound messages begin with an **RPC version tag**, represented as an unsigned, 32-bit integer. This version tag is the first part of the inbound message after the [empty delimeter frame](http://
delimiter is spelled wrong

2018-03-16 23:46 UTC, dcrankshaw commented on containers/container_implementation.md
> +### The current RPC version is: 3
Why 3?

2018-03-16 23:46 UTC, dcrankshaw commented on containers/container_implementation.md
> +           # Don't send the `SNDMORE` flag if this
This should read the opposite. Don't forget to **remove** the SNDMORE flag if this is the last message

2018-03-16 23:46 UTC, dcrankshaw commented on containers/container_implementation.md
> +Prediction requests are serialized in a similar fashion to prediction responses. The only difference is that prediction requests contain begin with an extra field.
remove "contain" (it should read "...requests begin with an extra field...")

2018-03-16 23:46 UTC, dcrankshaw commented on containers/python/rpc.py
> +                            inputs.append(input_item)
This section will conflict with the Python 3 changes. I'm going to merge the Python 3 code first, and then we can resolve the changes.

2018-03-16 23:46 UTC, dcrankshaw commented on containers/python/rpc.py
> +    header_buffer = bytearray(1024)
Will this create a new header buffer for every `PredictionResponse` object or reuse the same one?

2018-03-16 23:46 UTC, dcrankshaw commented on src/benchmarks/src/rpc_service_bench.cpp
>  #include <clipper/config.hpp>
Did you try running `rpc_service_bench`? I'm curious if it still works.

2018-03-16 23:46 UTC, dcrankshaw commented on src/container/include/container/container_rpc.hpp
> +    zmq::message_t msg_header_size(sizeof(sizeof(uint64_t)));
Why the repeated sizeof?

2018-03-16 23:46 UTC, dcrankshaw commented on src/libclipper/include/clipper/datatypes.hpp
> +using UniquePoolPtr = std::unique_ptr<T, void (*)(void *)>;
Can you add a note explaining what the ` void (*)(void *)` is?

2018-03-16 23:46 UTC, dcrankshaw commented on src/libclipper/include/clipper/datatypes.hpp
> +      : DataVector(data.release(), byte_size) {}
what does `data.release()` do?

2018-03-16 23:46 UTC, dcrankshaw commented on src/libclipper/include/clipper/util.hpp
> +  void push(T x) {
Why the removal of `const` here?

2018-03-16 23:46 UTC, dcrankshaw commented on src/libclipper/src/rpc_service.cpp
> +      output_header++;
nit: `output_header += 1`

2018-03-16 23:46 UTC, dcrankshaw commented on src/libclipper/test/metrics_test.cpp
> +  for (size_t i = 0; i < sample_size; i++) {
nit: s/i++/++i

2018-03-16 23:46 UTC, dcrankshaw commented on src/libclipper/test/selection_policies_test.cpp
> +  for (size_t i = 0; i < output_y_hat->size(); i++) {
nit: s/i++/++i

2018-03-16 23:46 UTC, dcrankshaw commented on src/libclipper/test/task_executor_test.cpp
> +  for (size_t i = 0; i < y_hat_a->size(); i++) {
nit: s/i++/++i

2018-03-16 23:47 UTC, dcrankshaw commented
jenkins test this please

2018-03-17 01:04 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1129/
Test FAILed.

2018-03-20 07:09 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1147/
Test FAILed.

2018-03-20 08:07 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1148/
Test FAILed.

2018-03-20 08:49 UTC, Corey-Zumar reviewed
@dcrankshaw Addressed your comments. I also implemented incorrect RPC version detection within the core Clipper system. We now log an error message if a container connects with an incorrect version. In order to ensure that the container RPC system reaches the point of execution where it sends model information to Clipper, we no longer crash the container when an incorrect version is detected; we only emit an error message within the container.

2018-03-20 08:49 UTC, Corey-Zumar commented on containers/R/rclipper_serve/src/container_rpc.hpp
> +constexpr uint32_t RPC_VERSION = 3;
This is the second significant overhaul of the RPC system, so it should correspond to the third version.

2018-03-20 08:49 UTC, Corey-Zumar commented on containers/container_implementation.md
> +All inbound messages begin with an **RPC version tag**, represented as an unsigned, 32-bit integer. This version tag is the first part of the inbound message after the [empty delimeter frame](http://
Thanks. Fixed.

2018-03-20 08:49 UTC, Corey-Zumar commented on containers/container_implementation.md
> +### The current RPC version is: 3
See related versioning comment

2018-03-20 08:49 UTC, Corey-Zumar commented on containers/container_implementation.md
> +           # Don't send the `SNDMORE` flag if this
Done.

2018-03-20 08:49 UTC, Corey-Zumar commented on containers/container_implementation.md
> +Prediction requests are serialized in a similar fashion to prediction responses. The only difference is that prediction requests contain begin with an extra field.
Thanks, fixed.

2018-03-20 08:49 UTC, Corey-Zumar commented on containers/python/rpc.py
> +                            inputs.append(input_item)
Sounds good!

2018-03-20 08:49 UTC, Corey-Zumar commented on containers/python/rpc.py
> +    header_buffer = bytearray(1024)
This will reuse the same buffer because `output_buffer` is a static object. https://stackoverflow.com/questions/68645/static-class-variables-in-python

The important thing to note is that we must access the variable independently of a specific `PredictionResponse` instance as `PredictionResponse.header_buffer`. This was not correctly implemented several months ago, and I recall merging a PR that fixed previous syntax issues.

2018-03-20 08:49 UTC, Corey-Zumar commented on src/benchmarks/src/rpc_service_bench.cpp
>  #include <clipper/config.hpp>
Good intuition. This did not work due to an issue with reusing `PredictionRequest` objects that was introduced by this PR. The problem was that inputs were moved out of the `PredictionRequest` object at serialization time (see old code: https://github.com/Corey-Zumar/clipper-1/blob/9b488cd514bdc961120354f3819189f1f00043a4/src/libclipper/src/datatypes.cpp#L197). This has been corrected by using a pointer copy instead of a move.

2018-03-20 08:49 UTC, Corey-Zumar commented on src/container/include/container/container_rpc.hpp
> +    zmq::message_t msg_header_size(sizeof(sizeof(uint64_t)));
This was a mistake. Fixed it here and in the R container.

2018-03-20 08:49 UTC, Corey-Zumar commented on src/libclipper/include/clipper/util.hpp
> +  void push(T x) {
Re-added const. The reference was removed in order to support the use of non-copyable objects with the queue.

2018-03-20 08:49 UTC, Corey-Zumar commented on src/libclipper/src/rpc_service.cpp
> +      output_header++;
Done.

2018-03-20 08:49 UTC, Corey-Zumar commented on src/libclipper/test/metrics_test.cpp
> +  for (size_t i = 0; i < sample_size; i++) {
Done

2018-03-20 08:49 UTC, Corey-Zumar commented on src/libclipper/test/selection_policies_test.cpp
> +  for (size_t i = 0; i < output_y_hat->size(); i++) {
Done

2018-03-20 08:49 UTC, Corey-Zumar commented on src/libclipper/test/task_executor_test.cpp
> +  for (size_t i = 0; i < y_hat_a->size(); i++) {
Done

2018-03-20 10:12 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1151/
Test FAILed.

2018-03-20 21:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1156/
Test FAILed.

2018-03-20 23:21 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1157/
Test PASSed.

2018-03-24 18:45 UTC, dcrankshaw approved these changes
LGTM. Fix the merge conflicts and we'll get this merged.

2018-03-24 21:16 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1171/
Test PASSed.

2018-03-26 23:24 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1174/
Test FAILed.

2018-03-27 00:05 UTC, dcrankshaw commented
jenkins test this please

2018-03-27 00:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1178/
Test FAILed.

2018-03-27 03:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1181/
Test FAILed.

2018-03-27 05:58 UTC, Corey-Zumar commented
jenkins test this please

2018-03-27 07:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1185/
Test FAILed.

2018-03-30 15:27 UTC, dcrankshaw commented
jenkins test this please

2018-03-30 16:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1220/
Test FAILed.

2018-04-04 16:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1261/
Test FAILed.

2018-04-04 17:31 UTC, dcrankshaw commented
jenkins test this please

2018-04-04 20:17 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1267/
Test FAILed.

2018-04-04 21:28 UTC, dcrankshaw commented
jenkins test this please

2018-04-04 22:31 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1269/
Test FAILed.

2018-04-05 21:51 UTC, Corey-Zumar commented
jenkins test this please

2018-04-05 23:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1282/
Test FAILed.

2018-04-06 00:29 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1283/
Test FAILed.

2018-04-06 04:12 UTC, Corey-Zumar commented
jenkins test this please

2018-04-06 08:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1290/
Test FAILed.

2018-04-07 03:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1310/
Test FAILed.

2018-04-08 03:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1315/
Test FAILed.

2018-04-08 17:43 UTC, dcrankshaw commented
@Corey-Zumar Does this PR change the type of the inputs we provide to user's models? Specifically, did `inputs` use to be a numpy array, and now it's a list? I thought it was previously a list as well, but I'm not sure. That was the issue with the mxnet test, and now I'm wondering if that's the current issue with the pytorch test.

2018-04-15 09:58 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1350/
Test FAILed.

2018-04-15 11:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1351/
Test FAILed.

2018-04-16 00:44 UTC, Corey-Zumar commented
jenkins test this please

2018-04-16 02:59 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1355/
Test FAILed.

2018-04-16 05:41 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1356/
Test FAILed.

2018-04-17 02:29 UTC, Corey-Zumar commented
jenkins test this please

2018-04-17 04:09 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1358/
Test FAILed.

2018-04-20 09:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1375/
Test FAILed.

2018-04-27 10:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1410/
Test FAILed.

2018-04-27 10:49 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1411/
Test FAILed.

2018-04-27 19:18 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1413/
Test FAILed.

2018-05-14 07:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1441/
Test FAILed.

2018-05-17 03:03 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1451/
Test FAILed.

2018-05-17 05:03 UTC, Corey-Zumar commented
jenkins test this please

2018-05-17 06:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1452/
Test FAILed.

2018-05-17 06:23 UTC, Corey-Zumar commented
jenkins test this please

2018-05-17 07:39 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1453/
Test FAILed.

2018-05-18 01:16 UTC, Corey-Zumar commented
jenkins test this please

2018-05-18 03:16 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1457/
Test FAILed.

2018-05-19 00:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1460/
Test FAILed.

2018-05-19 00:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1461/
Test FAILed.

2018-05-19 03:29 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1462/
Test FAILed.

2018-05-19 04:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1463/
Test FAILed.

2018-05-19 06:19 UTC, Corey-Zumar commented
jenkins test this please

2018-05-19 06:24 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1464/
Test FAILed.

2018-05-19 06:34 UTC, Corey-Zumar commented
jenkins test this please

2018-05-19 06:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1465/
Test FAILed.

2018-05-19 07:00 UTC, Corey-Zumar commented
jenkins test this please

2018-05-19 07:08 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1466/
Test FAILed.

2018-05-19 09:25 UTC, Corey-Zumar commented
jenkins test this please

2018-05-19 12:44 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1468/
Test FAILed.

2018-05-20 04:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1469/
Test FAILed.

2018-05-20 08:00 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1472/
Test FAILed.

2018-05-20 08:06 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1473/
Test FAILed.

2018-05-20 08:09 UTC, Corey-Zumar commented
jenkins test this please

2018-05-20 10:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1474/
Test FAILed.

2018-05-21 07:10 UTC, Corey-Zumar commented
jenkins test this please

2018-05-21 07:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1484/
Test FAILed.

2018-05-21 07:18 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1485/
Test FAILed.

2018-05-21 08:45 UTC, Corey-Zumar commented
jenkins test this please

2018-05-21 08:53 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1486/
Test FAILed.

2018-05-21 15:23 UTC, Corey-Zumar commented
jenkins test this please

2018-05-21 18:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1488/
Test FAILed.

2018-05-28 07:54 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1511/
Test FAILed.

2018-05-28 08:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1512/
Test FAILed.

2018-05-28 11:20 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1513/
Test PASSed.

2018-05-28 16:45 UTC, merged