Add support for XGBoost Model
ucbrise/clipper pull request #407
Opened 2018-02-08 09:20 UTC by RehanSD

Add support for XGBoost Model.

Currently integration tests show that the deployer is working; however, I get a 
```BuildError: pull access denied for clipper/xgboost-container, repository does not exist or may require 'docker login'``` Error, which I believe to be related to my docker setup, as well as an internal XGBoost error when training the model which I wish to discuss with Dan.

2018-02-08 09:25 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-02-12 21:22 UTC, dcrankshaw commented
jenkins ok to test

2018-02-12 21:39 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/994/
Test FAILed.

2018-02-12 22:23 UTC, Corey-Zumar requested changes
This is a really good start. I ran into an issue while running the integration test. Here's the stacktrace from within the container:

```
Attempting to run XGBoost container without installing dependencies
Contents of /model
environment.yml
func.pkl
modules
xgboost_model_data
Starting XGBoost container
Connecting to Clipper with default port: 7000
/model
Initializing XGBoost function container
Loading XGBoost model from /model
Failed to load XGBoost model from /model
[22:20:51] /feedstock_root/build_artefacts/xgboost_1516597594847/work/xgboost-0.7.post3/xgboost/dmlc-core/include/dmlc/./logging.h:300: [22:20:51] src/learner.cc:282: Check failed: fi->Read(&mparam, sizeof(mparam)) == sizeof(mparam) (0 vs. 136) BoostLearner: wrong model format

Stack trace returned 10 entries:
[bt] (0) /opt/conda/lib/python2.7/site-packages/xgboost/./lib/libxgboost.so(_ZN4dmlc15LogMessageFatalD1Ev+0x29) [0x7f162acd1ba9]
[bt] (1) /opt/conda/lib/python2.7/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11LearnerImpl4LoadEPN4dmlc6StreamE+0x171) [0x7f162ace0df1]
[bt] (2) /opt/conda/lib/python2.7/site-packages/xgboost/./lib/libxgboost.so(XGBoosterLoadModel+0x2c) [0x7f162ace56bc]
[bt] (3) /opt/conda/lib/python2.7/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f16434c5adc]
[bt] (4) /opt/conda/lib/python2.7/lib-dynload/../../libffi.so.6(ffi_call+0x1f2) [0x7f16434c5282]
[bt] (5) /opt/conda/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x4d6) [0x7f16436da736]
[bt] (6) /opt/conda/lib/python2.7/lib-dynload/_ctypes.so(+0x8a61) [0x7f16436d0a61]
[bt] (7) /opt/conda/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f1644885773]
[bt] (8) /opt/conda/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x190b) [0x7f164491953b]
[bt] (9) /opt/conda/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9) [0x7f16449214e9]
```

It looks like there's a parameter size error when the model is deserialized within the container. Do parameters need to be serialized and deserialized via a separate file? 

Let me know if you need help running or debugging the integration test.

2018-02-12 22:23 UTC, Corey-Zumar commented on dockerfiles/XGBoostContainerDockerfile
> +ARG CODE_VERSION
Nice dockerfile! Add it to the dockerfiles build script (https://github.com/ucbrise/clipper/blob/xgboost_model/bin/build_docker_images.sh) so that a container with name `clipper/xgboost-container` is built.

You can do this by adding an additional `create_image` directive at the bottom of the section where other deployer-related containers are built.

2018-02-12 22:23 UTC, Corey-Zumar commented on containers/python/xgboost_container_entry.sh
> +#!/usr/bin/env sh
Modify the permissions of this file via `sudo chmod 755 xgboost_container_entry.sh` and commit the result.

2018-02-12 22:23 UTC, Corey-Zumar commented on containers/python/xgboost_container.py
> +        model = XGBoost(model_path, input_type)
Change `XGBoost` to `XGBoostContainer`

2018-02-22 18:19 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1039/
Test FAILed.

2018-02-22 18:34 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1040/
Test FAILed.

2018-02-22 19:17 UTC, RehanSD commented
@dcrankshaw @Corey-Zumar In order to get around our issue where we would get `BoostLearner wrong model format` errors, I straight pickled and loaded the model. Discussing this with Dan, we realized that we don't need a docker container for xgboost if we just pickle the model, and so instead, I am shifting focus to adding an optional argument to clipper_admin.build_model() that will allow us to install extra deps (beyond the basic that come in the base image) into our model so that we can use xgboost, etc.

2018-03-09 18:28 UTC, dcrankshaw commented
Replaced by #431

2018-03-09 18:28 UTC, closed without merging