Query frontend fault tolerance2
ucbrise/clipper pull request #420
Opened 2018-02-25 02:08 UTC by rbala19

@dcrankshaw 

Here are the proposed changes for implementing query-frontend fault tolerance. These changes include polling for query-frontend downtime within kubernetes_container_manager.py and automatically redeploying any saved models to the newly deployed query-frontend.

2018-02-25 02:10 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-03-06 18:02 UTC, Jeffwan commented
Question: can you guarantee all query frontend instance have all deployed model instances? 
Once model is deployed, it is looking for CLIPPER_IP "query-frontend". I think models will connect to different QP pods so that every QP pod/instance has different model container associated? 

In that case, upper level prediction request might hit the QP which doesn't bind requested model. 

In your proposal, seems you assume all model containers will go to same QP instance behind QP service and this is the only one serving traffic. All other instances are just for fault tolerant? they are standby nodes and not serving traffic?

2018-03-09 03:28 UTC, dcrankshaw commented
@Jeffwan That's a really good point. This PR will actually bypass the Kubernetes service IP and provide the physical IP address of a specific query frontend replica to each container. Of course, in this case we need to manage failover ourselves in this case, because if a query frontend pod dies and is restarted by K8s, it may be assigned a new IP address. That's the reason this PR ended up being a little complicated.

2018-03-28 02:18 UTC, dcrankshaw requested changes
Added initial review

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/clipper_admin.py
> +from .docker.docker_container_manager import DockerContainerManager
Remove these imports

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/clipper_admin.py
> +    def upload_model_data(model_data_list):
Use this method instead of the version in the containermanagers, and it should not be static.

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/clipper_admin.py
> +            type = "docker"
Instead of doing the comparison here, add a method to `ContainerManager` called something like `get_container_manager_type()` and have docker return "docker" and K8s return "kubernetes". This lets the implementations self-identify and makes Clipper admin easier to extend.

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/clipper_admin.py
> +        # url = "http://{}/begin_polling".format(model_data['admin_addr'])
Uncomment this

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/container_manager.py
> +    def upload_model_data(self, model_data):
Delete this

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/docker/docker_container_manager.py
> +    def upload_model_data(self, model_data_list):
delete this

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
> +import traceback
Delete these imports

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
> -        # If an existing Redis service isn't provided, start one
Don't delete code comments

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
> +        self._k8s_beta.patch_namespaced_deployment_scale(
Rather than patching after the deployment is started, just modify the initial deployment spec

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
> +        logger.info("Posted successfully")
Delete this

2018-03-28 02:18 UTC, dcrankshaw commented on clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
> +                                    CLIPPER_DOCKER_LABEL:
Let's add another label here like:

```py
CLIPPER_MODEL_CONTAINER_QUERY_FRONTEND_IP = "ai.clipper..."
'labels': {..., CLIPPER_MODEL_CONTAINER_QUERY_FRONTEND_IP: clipper_ip, ...}
```

2018-03-28 02:18 UTC, dcrankshaw commented on mgv2/Dockerfile
> +COPY ./mgv2/config /home/.kube/
Don't copy the config in. Check out [this issue](https://github.com/kubernetes-client/python/issues/254) for accessing K8s api from within a pod.

2018-03-28 02:18 UTC, dcrankshaw commented on mgv2/mgv2.py
> +class Mgv2():
If all the methods are static, you probably don't need a class at all

2018-03-28 02:18 UTC, dcrankshaw commented on mgv2/mgv2.py
> +    config.load_kube_config()
Change this to load the in cluster config

2018-03-28 02:18 UTC, dcrankshaw commented on mgv2/mgv2.py
> +    @app.route('/get_query_to_model_mapping', methods=['GET', 'POST'])
Delete the "GET" method

2018-03-28 02:18 UTC, dcrankshaw commented on mgv2/mgv2.py
> +            logger.info("Query_to_model_mapping: {}".format(query_to_model_mapping))
Refactor the rest of this method into a separate method that takes the `query_to_model_mapping` dict. Then you can both call it here, and after you call deploy_model in `reassign...`

2018-03-31 12:17 UTC, rbala19 commented
@dcrankshaw I addressed all the changes in the review. I performed all testing locally; I did not perform any tests where I deployed the mgv2 image to kubernetes. If you want to enable a local testing environment, uncomment the lines 1086 (clipper_admin.py),  1104 (clipper_admin.py), and 50 (mgv2.py) and comment the lines 1087 (clipper_admin.py), 1104 (clipper_admin.py), 49 (mgv2.py). These lines have to do with mgv2 URL creation and config loading. 

To test locally, you must also deploy a redis server using the command redis-server on terminal. To test locally, I start mgv2.py, then start clipper through the ipynb. Then I can add models through ipynb or take down frontends using kubectl delete 

One major omission is the feature that stops models on downed frontends. We discussed adding labels, for which I made the code changes, but there is an error with the syntax of the label selector in "stop_models_on_dead_ip" that I can't seem to figure out. I have caught the exception this call throws and it displays the stacktrace every time deploy_model is called within mgv2.py, in case that information will be helpful for debugging.

Please let me know if you have any further questions.

2018-04-13 20:15 UTC, dcrankshaw commented
@simon-mo figured out a better way to do this, and so this has been replaced by #462

2018-04-13 20:15 UTC, closed without merging