Implement Metric Server
ucbrise/clipper pull request #440
Opened 2018-03-18 01:41 UTC by simon-mo

Implement the metric server described in #423. This will solves issue #401 and #412. 

Note:
- No test is needed because we replaced the original model container metrics with the new design. That's sufficient for testing the new implementation.
- Extensive API Docs are added for client facing functions.

2018-03-18 01:52 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1135/
Test FAILed.

2018-03-18 02:54 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1136/
Test FAILed.

2018-03-18 04:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1137/
Test FAILed.

2018-03-18 05:24 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1138/
Test FAILed.

2018-03-19 00:02 UTC, simon-mo commented
jenkins test this please

2018-03-19 00:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1141/
Test FAILed.

2018-03-20 05:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1146/
Test FAILed.

2018-03-20 08:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1149/
Test FAILed.

2018-03-20 08:37 UTC, simon-mo commented
I just added another package and conda seg fault again?! 😟

2018-03-20 08:37 UTC, simon-mo commented
jenkins test this please

2018-03-20 09:55 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1150/
Test FAILed.

2018-03-20 12:10 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1153/
Test FAILed.

2018-03-20 12:55 UTC, simon-mo commented
jenkins test this please

2018-03-20 14:06 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1154/
Test FAILed.

2018-03-20 16:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1155/
Test FAILed.

2018-03-20 23:59 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1158/
Test FAILed.

2018-03-21 00:00 UTC, simon-mo commented
jenkins test this please

2018-03-21 00:00 UTC, simon-mo commented
^seg-fault again

2018-03-21 01:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1159/
Test FAILed.

2018-03-21 02:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1160/
Test FAILed.

2018-03-21 02:22 UTC, simon-mo commented
jenkins test this please

2018-03-21 02:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1161/
Test FAILed.

2018-03-21 06:13 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1163/
Test FAILed.

2018-03-21 17:28 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1164/
Test FAILed.

2018-03-21 18:59 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1165/
Test PASSed.

2018-03-24 19:06 UTC, dcrankshaw requested changes
This is awesome!  I just have a couple minor comments.

Also, how hard would it be to add this to the model containers in other languages (e.g. Java)? Can you file an issue to remind us to do this?

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/__init__.py
> +from . import metric
Change `metric` to `metrics`?

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metric/__init__.py
> +    server.start_redis_daemon()
Will this start a Redis daemon any time `clipper_admin` is imported?

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metric/client.py
> +    messege_dict = {
typo: s/messege/message

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metric/client.py
> +        The value of metric to be reported. The value must be able to be casted
change the second sentence to "...must be able to be cast to float."

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metric/client.py
> +    assert name in metric_pool, "{} has not been added. \
Instead of using an assert, can you raise an exception?

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metric/client.py
> +    assert metric_type in set(
Change assert to raising an exception

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metric/server.py
> +def handle_messege(messege_dict, metric_pool):
s/messege/message

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metric/server.py
> +    Handle a messege dictionary, dispatch request to add or report call
s/messege/message

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metric/server.py
> +    for messege in sub.listen():  # Blocking, will run forever
s/messege/message

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metric/server.py
> +            handle_messege(messege_dict, metric_pool)
s/messege/message

2018-03-24 19:06 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metric/server.py
> +        except Exception as e:
Do you want to catch all exceptions here? Or would it make sense to be more specific about which exceptions to catch?

2018-03-26 23:37 UTC, simon-mo commented on clipper_admin/clipper_admin/metric/__init__.py
> +    server.start_redis_daemon()
You are correct. I just deleted `from . import metrics` in `__init__.py`. 

Now only when users type `import clipper_admin.metrics as metrics`, the redis server will be started (which is the expected behavior)

2018-03-27 00:06 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1177/
Test FAILed.

2018-03-27 00:21 UTC, simon-mo commented
Jenkins test this please

2018-03-27 02:33 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1179/
Test FAILed.

2018-03-28 05:43 UTC, simon-mo commented
Jenkins test this please

2018-03-28 08:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1191/
Test FAILed.

2018-03-29 20:39 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1202/
Test FAILed.

2018-03-30 15:12 UTC, dcrankshaw commented
jenkins test this please

2018-03-30 15:21 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1218/
Test FAILed.

2018-03-30 15:27 UTC, dcrankshaw commented
jenkins test this please

2018-03-30 15:30 UTC, dcrankshaw approved these changes
LGTM

2018-03-30 15:49 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1219/
Test FAILed.

2018-03-30 19:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1223/
Test FAILed.

2018-03-30 20:06 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1224/
Test FAILed.

2018-03-30 21:26 UTC, dcrankshaw commented
jenkins test this please

2018-03-30 23:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1226/
Test FAILed.

2018-03-31 00:01 UTC, dcrankshaw commented
jenkins test this please

2018-03-31 00:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1228/
Test FAILed.

2018-04-03 21:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1256/
Test FAILed.

2018-04-04 03:55 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1257/
Test FAILed.

2018-04-04 05:12 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1258/
Test FAILed.

2018-04-04 08:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1259/
Test FAILed.

2018-04-04 11:50 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1260/
Test FAILed.

2018-04-04 15:40 UTC, dcrankshaw requested changes
I have no idea why the tests are failing. I'm trying to reproduce locally.

2018-04-04 15:40 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metrics/config.py
> +API_VERSION = "0.3.0"  # Consistent with Clipper Version.
Can you import this from `clipper_admin.__version__`?

2018-04-04 15:40 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metrics/schema.py
> +versions = ['0.3.0']
Import from Clipper admin version, don't hardcode version numbers

2018-04-04 15:40 UTC, dcrankshaw commented on clipper_admin/clipper_admin/metrics/schema.py
> +def validate_schema(messege_dict):
message is still spelled wrong here

2018-04-04 15:40 UTC, dcrankshaw commented on containers/python/rpc.py
> +from subprocess import Popen, PIPE
Use `subprocess32` instead of `subprocess`

2018-04-04 16:07 UTC, dcrankshaw commented
jenkins test this please

2018-04-04 17:11 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1262/
Test FAILed.

2018-04-04 17:47 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1265/
Test FAILed.

2018-04-04 18:57 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1266/
Test FAILed.

2018-04-05 00:03 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1270/
Test FAILed.

2018-04-05 02:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1271/
Test FAILed.

2018-04-05 06:02 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1274/
Test FAILed.

2018-04-05 20:26 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1278/
Test PASSed.

2018-04-05 21:04 UTC, dcrankshaw approved these changes
lgtm

2018-04-05 21:04 UTC, merged