Added functionality to query previous version models
ucbrise/clipper pull request #454
Opened 2018-03-28 05:33 UTC by daminig

2018-03-28 05:35 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-03-29 16:36 UTC, dcrankshaw commented
jenkins add to whitelist

2018-03-29 16:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1200/
Test FAILed.

2018-03-30 01:42 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1209/
Test FAILed.

2018-03-30 03:17 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1211/
Test FAILed.

2018-03-30 08:57 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1214/
Test FAILed.

2018-03-30 09:37 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1215/
Test FAILed.

2018-03-30 10:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1216/
Test FAILed.

2018-03-30 10:37 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1217/
Test FAILed.

2018-04-03 15:36 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1253/
Test FAILed.

2018-04-05 02:36 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1272/
Test FAILed.

2018-04-05 21:36 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1279/
Test FAILed.

2018-04-05 21:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1280/
Test FAILed.

2018-04-05 21:49 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1281/
Test FAILed.

2018-04-06 04:04 UTC, dcrankshaw requested changes
This looks good. Just some minor cleanup.

2018-04-06 04:04 UTC, dcrankshaw commented on integration-tests/clipper_admin_tests.py
> +            return 2
These predict functions won't work like this. Modify them to be
```py
def predict_func1(xs):
    return ["1" for _ in xs]

def predict_func2(xs):
    return ["2" for _ in xs]
```

2018-04-06 04:04 UTC, dcrankshaw commented on integration-tests/clipper_admin_tests.py
> +        self.assertEqual([pred1['output']], 1)
Change this to be `self.assertEqual([pred1['output']], "1")`

2018-04-06 04:04 UTC, dcrankshaw commented on integration-tests/clipper_admin_tests.py
> +        self.assertEqual([pred2['output']], 2)
Change to `self.assertEqual([pred2['output']], "2")`

2018-04-06 04:04 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +          models = clipper::redis::get_model_versions(redis_connection_, name);
You need to acquire the mutex here:

```cpp
std::unique_lock<std::mutex> l(current_model_versions_mutex_);
```

2018-04-06 04:04 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +            std::unique_lock<std::mutex> (current_model_versions_mutex_);
This syntax isn't quite right. It should be 
```cpp
std::unique_lock<std::mutex> l(current_model_versions_mutex_);
```

Note the **l** before `(current_model_versions_mutex)`

2018-04-06 04:30 UTC, dcrankshaw approved these changes
LGTM. Will merge once the tests pass.

2018-04-06 08:45 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1291/
Test FAILed.

2018-04-10 03:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1330/
Test FAILed.

2018-04-11 08:31 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1335/
Test FAILed.

2018-04-13 21:59 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1340/
Test FAILed.

2018-04-24 21:04 UTC, dcrankshaw requested changes
Can we get this compiling and passing the format checker soon?

2018-04-24 21:54 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1390/
Test FAILed.

2018-04-27 08:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1406/
Test FAILed.

2018-04-27 09:47 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1408/
Test FAILed.

2018-04-27 10:03 UTC, daminig commented
jenkins test this please

2018-04-27 10:47 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1409/
Test FAILed.

2018-05-04 21:19 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1414/
Test FAILed.

2018-05-04 22:48 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1415/
Test FAILed.

2018-05-10 23:24 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1420/
Test FAILed.

2018-05-11 01:58 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1422/
Test FAILed.

2018-05-11 15:43 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1429/
Test FAILed.

2018-05-11 15:55 UTC, dcrankshaw commented
jenkins test this please

2018-05-11 16:06 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1431/
Test FAILed.

2018-05-11 16:10 UTC, dcrankshaw approved these changes
I fixed this PR up, and it should be good to go once the tests pass.

2018-05-12 00:36 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1435/
Test FAILed.

2018-05-15 04:07 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1444/
Test PASSed.

2018-05-15 17:26 UTC, merged