Query Frontend Scale-out via Kubernetes Service
ucbrise/clipper pull request #462
Opened 2018-04-06 09:41 UTC by simon-mo

In this PR we implement Query frontend scale-out/fault tolerance using Kubernetes services:

1. We add a rpc-facing service to each query frontend
2. When we add/set model replicas, we do so in per query frontend basis

2018-04-06 17:09 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1299/
Test PASSed.

2018-04-06 19:22 UTC, simon-mo commented
StateDB test in libclipper test failed. Let me try restart.
Also, there are tons of caffe compiler warning.

2018-04-06 19:22 UTC, simon-mo commented
jenkins test this please

2018-04-06 19:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1300/
Test FAILed.

2018-04-06 22:47 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1304/
Test FAILed.

2018-04-06 23:46 UTC, simon-mo commented
@dcrankshaw Can you add the following image to amazon's container service?
```
18-04-06:20:49:41 INFO     [clipper_admin.py:412] Pushing model Docker image to 568959175238.dkr.ecr.us-west-1.amazonaws.com/clipper/kube-frontends-model:1
```

2018-04-08 07:44 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1318/
Test FAILed.

2018-04-08 07:48 UTC, simon-mo commented
jenkins test this please

2018-04-08 08:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1320/
Test FAILed.

2018-04-10 02:38 UTC, simon-mo commented
jenkins test this please

2018-04-10 04:41 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1331/
Test FAILed.

2018-04-14 02:43 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1344/
Test FAILed.

2018-04-18 03:43 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1360/
Test FAILed.

2018-04-20 03:15 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1365/
Test FAILed.

2018-04-20 03:23 UTC, simon-mo commented
jenkins test this please

2018-04-20 04:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1368/
Test FAILed.

2018-04-20 05:05 UTC, simon-mo commented
jenkins test this please

2018-04-20 05:06 UTC, simon-mo commented
Note to self:
```
Building clipper/query_frontend:478f01c from file QueryFrontendDockerfile
Sending build context to Docker daemon  240.5MB

Step 1/6 : ARG CODE_VERSION
 ---> 
Step 2/6 : FROM clipper/lib_base:${CODE_VERSION}
 ---> 6a819c93baf5
Step 3/6 : LABEL maintainer "Dan Crankshaw <dscrankshaw@gmail.com>"
 ---> Using cache
 ---> 4d1d5dae16ea
Step 4/6 : COPY ./ /clipper
 ---> 1cbd76ab1771
Removing intermediate container ab664780cf0a
Step 5/6 : RUN cd /clipper/src/libs/spdlog     && git apply ../patches/make_spdlog_compile_linux.patch     && cd /clipper     && ./configure --cleanup-quiet     && ./configure --release     && cd release     && make -j4 query_frontend
 ---> Running in 787f5a53dd92
grpc: the connection is unavailable
```
If the error persist, investigate.

2018-04-20 06:24 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1371/
Test FAILed.

2018-04-20 15:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1378/
Test FAILed.

2018-04-21 01:50 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1384/
Test PASSed.

2018-04-21 17:05 UTC, dcrankshaw requested changes
This looks great. I just had a couple super minor comments.

2018-04-21 17:05 UTC, dcrankshaw commented on clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
> +from six.moves import range
I removed the `six` package from Clipper's `setup.py` in the python 3 PR, so keep an eye on that when you merge.

2018-04-21 17:05 UTC, dcrankshaw commented on clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
> +                        #   service.
👍

2018-04-21 17:05 UTC, dcrankshaw commented on dockerfiles/Caffe2OnnxDockerfile
> +#RUN git clone --recursive https://github.com/caffe2/caffe2.git && cd caffe2 \
You probably don't want to comment this out, as the Docker container won't work without it. We just want to not build the container in `build_docker_images.sh`. That way when we can add back support, we can just uncomment the line in that script.

2018-04-21 17:05 UTC, dcrankshaw commented on integration-tests/kubernetes_multi_frontend.py
> +        4,  # Version 4 to avoid container caching
This seems brittle. Want to pick a random string instead? Versions can be arbitrary strings.

2018-04-26 06:35 UTC, simon-mo commented on clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
> +from six.moves import range
Right... I can just delete this line because python2 can also do `range`. (It's eager though, but not important in our case)

2018-04-26 10:17 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1394/
Test FAILed.

2018-04-27 01:38 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1400/
Test FAILed.

2018-04-27 01:51 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1402/
Test FAILed.

2018-04-27 03:23 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1403/
Test PASSed.

2018-05-11 15:59 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1430/
Test FAILed.

2018-05-11 16:09 UTC, dcrankshaw approved these changes
lgtm

2018-05-11 23:40 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1434/
Test FAILed.

2018-05-11 23:57 UTC, dcrankshaw commented
jenkins test this please

2018-05-12 03:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1436/
Test PASSed.

2018-05-14 17:03 UTC, merged