Fix an infinite loop of GarbageCollectionThread
ucbrise/clipper pull request #481
Opened 2018-04-23 00:42 UTC by withsmilo

* Changed list
  * TaskExecutionThread's worker calls try_pop() to spin.
  * GarbageCollectionThread's worker calls wait_pop() to block.
* related issue: #468

2018-04-23 00:45 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-04-24 20:53 UTC, dcrankshaw commented
jenkins ok to test

2018-04-24 20:59 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1389/
Test FAILed.

2018-04-24 21:02 UTC, dcrankshaw requested changes
Thanks for tracking this down! Just had a minor comment for improving the usability of `ThreadPool` in the future.

2018-04-24 21:02 UTC, dcrankshaw commented on src/libclipper/include/clipper/threadpool.hpp
> +  bool is_block_worker_ = true;
Rather than hardcoding this to one, can you make it a constructor argument, and then set it to `true` in `GarbageCollectionThreadpool::getThreadPool` where we call the `FixedSizeThreadpool` constructor? Whether the worker should block or not is a result of the semantics of the GarbageCollector, not a fundamental part of the FixedSizeThreadpool semantics.

2018-04-25 14:57 UTC, withsmilo commented on src/libclipper/include/clipper/threadpool.hpp
> +  bool is_block_worker_ = true;
Good review. I will try to modify it.

2018-05-14 02:20 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1438/
Test FAILed.

2018-05-14 02:37 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1439/
Test FAILed.

2018-05-14 06:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1440/
Test FAILed.

2018-05-14 22:52 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1442/
Test PASSed.

2018-05-15 20:18 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1446/
Test FAILed.

2018-05-15 22:41 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1447/
Test FAILed.

2018-05-16 01:34 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1448/
Test PASSed.

2018-05-16 19:35 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1449/
Test PASSed.

2018-05-16 22:24 UTC, dcrankshaw approved these changes
lgtm

2018-05-16 22:25 UTC, merged