[DO NOT MERGE] Logging
ucbrise/clipper pull request #52
Opened 2017-01-24 07:42 UTC by Corey-Zumar

Leaving this here for initial review of logging infrastructure.

TODO:

Write tests
Write docs
Make spdlog a git submodule

2017-01-24 07:51 UTC, Corey-Zumar commented
Here's how logging currently looks:
```
  clipper::Logger::get().log_error("Redis", "Clipper failed to connect to Redis", "Retrying in 1 second...");
  clipper::Logger::get().log_info("Redis", "Connected to Redis successfully!");
  const std::string key = "sample_key";
  const std::string event_type = "sample_type";
  clipper::Logger::get().log_info_formatted(
      "Redis", "APPLICATION EVENT DETECTED. Key: {}, event_type: {}", key, event_type);
  clipper::Logger::get().log_info("RPC", "Starting RPC service...");
  clipper::Logger::get().log_error("RPC", "Failed to start RPC service");
```
<=>
<img width="720" alt="screen shot 2017-01-23 at 11 51 11 pm" src="https://cloud.githubusercontent.com/assets/5203667/22238537/e21e410a-e1c6-11e6-8934-f678c887b9ee.png">

2017-01-26 11:06 UTC, Corey-Zumar commented
@dcrankshaw This is ready for your review - no longer WIP

2017-01-30 20:53 UTC, dcrankshaw requested changes
Looks good! How do you specify the log level at runtime? E.g. what if I want to only see log messages that are WARN or above?

2017-01-30 20:53 UTC, dcrankshaw commented on src/frontends/src/query_frontend.hpp
> +const std::string LOGGING_TAG_QUERY_FRONTEND = "QURYFRNTD";
Let's leave the vowels in.

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/include/clipper/logging.hpp
> +  template<class ...Args>
What's the difference between a formatted and unformatted message?

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/include/clipper/logging.hpp
> +  template<class ...Args>
Move the template declaration below the comment

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/include/clipper/logging.hpp
> +  template<class ...Strings>
template below comment

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/include/clipper/logging.hpp
> +  template<class ...Args>
template below comment

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/include/clipper/query_processor.hpp
> +const std::string LOGGING_TAG_QUERY_PROCESSOR = "QRYPROCSSR";
Put the vowels in

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
> +const std::string LOGGING_TAG_TASK_EXECUTOR = "TaskExec";
s/TaskExec/TASKEXECUTOR

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/include/clipper/logging.hpp
> +// Defines the logging format as [HH:MM:SS.mmm][<LOG_LEVEL_1_CHAR>] <Message>
Can we use the full log level (e.g. INFO and ERROR instead of I and E)?

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/include/clipper/logging.hpp
> +static constexpr uint MAX_TAG_LENGTH = 10;
Is there a reason to have the max tag length 10?

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/include/clipper/logging.hpp
> +
Can you add static convenience functions for log_debug, log_info, etc. that wrap the call to `Logger::get().log_*`?

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/include/clipper/selection_policy.hpp
> +const std::string LOGGING_TAG_SELECTION_POLICY = "SELECTPLCY";
vowels

2017-01-30 20:53 UTC, dcrankshaw commented on src/libclipper/src/logging.cpp
> +    spdlog::set_async_mode(8192, spdlog::async_overflow_policy::block_retry);
What's 8192?

2017-01-31 10:51 UTC, Corey-Zumar commented on src/libclipper/include/clipper/logging.hpp
> +static constexpr uint MAX_TAG_LENGTH = 10;
More generally, a maximum tag length is required to preserve the alignment of log messages. Should I increase the length from 10?

2017-01-31 10:57 UTC, Corey-Zumar commented on src/libclipper/include/clipper/logging.hpp
> +  template<class ...Strings>
Done

2017-01-31 10:57 UTC, Corey-Zumar commented on src/libclipper/include/clipper/logging.hpp
> +  template<class ...Args>
Done

2017-01-31 10:57 UTC, Corey-Zumar commented on src/libclipper/include/clipper/logging.hpp
> +  template<class ...Args>
Done

2017-01-31 10:58 UTC, Corey-Zumar commented on src/libclipper/include/clipper/query_processor.hpp
> +const std::string LOGGING_TAG_QUERY_PROCESSOR = "QRYPROCSSR";
Done

2017-01-31 10:58 UTC, Corey-Zumar commented on src/libclipper/include/clipper/task_executor.hpp
> +const std::string LOGGING_TAG_TASK_EXECUTOR = "TaskExec";
Done

2017-01-31 10:58 UTC, Corey-Zumar commented on src/libclipper/include/clipper/selection_policy.hpp
> +const std::string LOGGING_TAG_SELECTION_POLICY = "SELECTPLCY";
Done

2017-01-31 11:04 UTC, Corey-Zumar commented on src/libclipper/src/logging.cpp
> +    spdlog::set_async_mode(8192, spdlog::async_overflow_policy::block_retry);
This method indicates that all logging should occur asynchronously. `8192` is the size of the asynchronous queue that is used to process log messages, in elements. This results in a logging buffer that is roughly 800KB in size. For more information, see https://github.com/gabime/spdlog/wiki/6.-Asynchronous-logging

I've added comments to this effect in both locations where this method is called.

2017-01-31 12:12 UTC, Corey-Zumar commented on src/frontends/src/query_frontend.hpp
> +const std::string LOGGING_TAG_QUERY_FRONTEND = "QURYFRNTD";
Done

2017-01-31 12:13 UTC, Corey-Zumar commented on src/libclipper/include/clipper/logging.hpp
> +// Defines the logging format as [HH:MM:SS.mmm][<LOG_LEVEL_1_CHAR>] <Message>
Done! This required a few changes in order to preserve alignment. I've created a `LogLevel` enum and several constants defining the lengths of the different log level tags. These values are used to pad log messages of different levels correctly.

2017-01-31 12:35 UTC, Corey-Zumar commented on src/libclipper/include/clipper/logging.hpp
> +
Done! Changed all instances of `Logger::get().log_*` to `log_*`

2017-01-31 12:41 UTC, Corey-Zumar commented on src/libclipper/include/clipper/logging.hpp
> +  template<class ...Args>
A formatted message takes format arguments. For example, `"The number {}", 5` is a formatted message. The result of the call
`log_info_formatted("TAG", "The number {}", 5)` 
is a log containing the message `"The number 5"`.

 Is there a better word for this?

2017-01-31 12:45 UTC, Corey-Zumar commented
@dcrankshaw addressed your comments

2017-01-31 17:15 UTC, dcrankshaw commented on src/libclipper/include/clipper/logging.hpp
> +  template<class ...Args>
No that's fine. Makes sense.

2017-01-31 17:39 UTC, dcrankshaw approved these changes

2017-01-31 17:39 UTC, dcrankshaw commented
LGTM

2017-01-31 17:39 UTC, merged