Revert namespace in build_docker_images.sh
ucbrise/clipper pull request #526
Opened 2018-07-01 12:41 UTC by withsmilo

`docker info` no longer shows username information for the DockerHub Registry. So 'namespace' must be reverted to build Clipper images.

2018-07-01 12:43 UTC, withsmilo commented
@simon-mo 
My Docker's version is 18.03.1-ce-mac65 (24312). What is the version of your Docker?

2018-07-01 12:45 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2018-07-01 22:22 UTC, simon-mo commented
@withsmilo Thanks for the fix.

It turns out docker won't printout Username if the platform is Mac but it will printout username if the platform is linux. 

We still need this line for integration tests on jenkins though. I left a comment for workaround.

2018-07-01 22:24 UTC, simon-mo requested changes

2018-07-01 22:24 UTC, simon-mo commented on bin/build_docker_images.sh
> +namespace="clipper"
Can you do:
```
# See PR #562
if [[ $OSTYPE == darwin* ]]
then 
    namespace="clipper"
else
     namespace=$(docker info | grep Username | awk '{ print $2 }')
fi;
```

2018-07-02 00:44 UTC, withsmilo commented on bin/build_docker_images.sh
> +namespace="clipper"
@simon-mo : I pushed your codes to this PR. Thank you!

2018-07-02 00:57 UTC, simon-mo commented
jenkins ok to test

2018-07-02 02:35 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1630/
Test FAILed.

2018-08-15 14:31 UTC, withsmilo commented
The error message by Jenkins is here,
```
18-07-02:02:34:43 ERROR    [clipper_metric_docker.py:126] Wrong number of targets
```
I think that my PR didn't affect `clipper_metric_docker` of the integration test.

2019-03-22 00:58 UTC, withsmilo commented
dropped because this PR is too old.

2019-03-22 00:58 UTC, closed without merging