Modify clipper manager to provide option for local execution
ucbrise/clipper pull request #60
Opened 2017-02-05 11:18 UTC by Corey-Zumar

Enables clipper manager to be used to manage clipper locally. Specifying a host of `127.0.0.1` or `localhost` at initialization indicates local launch

2017-02-05 11:21 UTC, Corey-Zumar commented
@dcrankshaw

2017-02-05 13:56 UTC, Corey-Zumar commented
Needs work - model deployment doesn't function locally

2017-02-06 23:27 UTC, Corey-Zumar commented
Ready for review

2017-02-08 05:52 UTC, dcrankshaw reviewed
Once the demo code goes in I want to run through and test it. But so far looks good.

2017-02-08 05:52 UTC, dcrankshaw commented on management/clipper_manager.py
> +    def host_is_local(self):
Since these are private methods can you prefix them with _. E.g. `host_is_local` to `_host_is_local`

2017-02-08 05:52 UTC, dcrankshaw commented on management/clipper_manager.py
> +    def start_docker_if_necessary(self):
prefix with _

2017-02-08 05:54 UTC, dcrankshaw commented
Reminder to add a note about how to running the Clipper demo locally in this PR once #55 gets merged.

2017-02-08 06:26 UTC, Corey-Zumar commented on management/clipper_manager.py
> +    def host_is_local(self):
Done

2017-02-08 06:26 UTC, Corey-Zumar commented on management/clipper_manager.py
> +    def start_docker_if_necessary(self):
Done

2017-02-08 07:55 UTC, dcrankshaw requested changes
Found a couple minor bugs. Otherwise all looks good!

2017-02-08 07:55 UTC, dcrankshaw commented on management/clipper_manager.py
>      def __init__(self, host, user, key_path):
Let's make user and keypath optional arguments. If not local, complain if they're not provided.

Make sure to note that in the method documentation above as well.

2017-02-08 07:55 UTC, dcrankshaw commented on management/clipper_manager.py
> +    def _host_is_local(self):
Can you add `"local"` as an acceptable keyword?

2017-02-08 07:55 UTC, dcrankshaw commented on management/clipper_manager.py
> +        if self.host_is_local():
s/host_is_local/_host_is_local

You're missing an underscore 😃

2017-02-08 07:55 UTC, dcrankshaw commented on management/clipper_manager.py
> +                    shutil.copy2(local_path, remote_path)
You need `import shutil` at the top of this file

2017-02-08 08:06 UTC, Corey-Zumar reviewed
Addressed comments

2017-02-08 08:06 UTC, Corey-Zumar commented on management/clipper_manager.py
> +                    shutil.copy2(local_path, remote_path)
Done

2017-02-08 08:06 UTC, Corey-Zumar commented on management/clipper_manager.py
> +        if self.host_is_local():
Fixed

2017-02-08 08:06 UTC, Corey-Zumar commented on management/clipper_manager.py
>      def __init__(self, host, user, key_path):
Done!

2017-02-08 08:06 UTC, Corey-Zumar commented on management/clipper_manager.py
> +    def _host_is_local(self):
Done!

2017-02-08 08:17 UTC, dcrankshaw approved these changes

2017-02-08 08:19 UTC, merged