Performance / Resilience Test Based on CIFAR Demo
ucbrise/clipper pull request #68
Opened 2017-02-17 07:53 UTC by Corey-Zumar

2017-02-17 07:53 UTC, Corey-Zumar commented
@dcrankshaw

2017-02-17 07:55 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-02-17 16:19 UTC, dcrankshaw commented
jenkins test this please

2017-02-17 16:22 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/38/
Test FAILed.

2017-02-22 00:23 UTC, dcrankshaw commented
jenkins, test this please

2017-02-22 00:30 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/40/
Test FAILed.

2017-02-22 00:35 UTC, dcrankshaw commented
@Corey-Zumar Looks like there's a problem with Jenkins, don't worry about the failing tests for now. I'm reviewing this right now.

2017-02-22 05:07 UTC, shaneknapp commented
test this please

2017-02-22 05:29 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/44/
Test PASSed.

2017-02-22 21:11 UTC, shaneknapp commented
test this please

2017-02-22 21:17 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/45/
Test FAILed.

2017-02-22 21:20 UTC, shaneknapp commented
test this please

2017-02-22 21:32 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/46/
Test PASSed.

2017-02-27 19:27 UTC, dcrankshaw requested changes
This is a good start. There's a bug in the benchmark code though, so I haven't been able to actually get through the full benchmark.

Also, can you format and lint the Python code to make sure it conforms with PEP8?

2017-02-27 19:27 UTC, dcrankshaw commented on bench/bench_init.py
> +	setup = BenchSetup("localhost", "../examples/cifar_demo")
Can you have the location of the CIFAR dataset be a command line argument?

2017-02-27 19:27 UTC, dcrankshaw commented on bench/bench_init.py
> +		model_location = BASE_DATA_PATH + SKLEARN_MODEL_FILE
use `os.path.join()` not string concatenation

2017-02-27 19:27 UTC, dcrankshaw commented on bench/bench_init.py
> +import requests
json and requests imports aren't used

2017-02-27 19:27 UTC, dcrankshaw commented on bench/bench_init.py
> +
Get rid of the tabs in this file

2017-02-27 19:27 UTC, dcrankshaw commented on bench/bench_init.py
> +
In order to get the imports to work correctly, I added the following files
```
management/__init__.py
examples/__init__.py
examples/tutorial/__init__.py
```

Then I changed the imports to the following:
```py
sys.path.append(os.path.abspath("../management"))
sys.path.append(os.path.abspath("../examples"))

import clipper_manager
from tutorial import cifar_utils
from sklearn import linear_model as lm
from sklearn.externals import joblib
from fabric.api import *
```

2017-02-27 19:27 UTC, dcrankshaw commented on bench/bench_init.py
> +
We will want to rethink directory organization in the future, but for now this should work. I don't want an __init__.py file in the root of the source code.

2017-02-27 19:27 UTC, dcrankshaw commented on bench/bench_init.py
> +BASE_DATA_PATH = "data/"
This is confusingly named, because this is where the model, not the data, will be stored.

Change it to:

```py
BASE_MODEL_PATH = model/"
```

2017-02-27 19:27 UTC, dcrankshaw commented on bench/bench_init.py
> +			joblib.dump(model, model_location)
This will fail if `BASE_DATA_PATH` doesn't exist yet. Add a check to see if the directory exists, and if it doesn't, create it.

2017-02-27 19:27 UTC, dcrankshaw commented on src/frontends/src/bench.cpp
> +};
Reading from the command-line is really nice for one-off benchmarks but impossible to script.

Can you a command line arg `-f FILENAME.json` that reads a JSON config file to get the benchmark parameters. We already have a command line options library in the codebase, check out [`query_frontend_main.cpp`](https://github.com/ucbrise/clipper/blob/35cb8ee0a9fe8f8ea8601d06b8cc8adcfe2fc227/src/frontends/src/query_frontend_main.cpp#L2-L18) for an example on how to use it.

The behavior should be to first parse command line args. If the filename arg is present, read the JSON file to get the benchmark params. If it's not present, use the existing approach of asking the user interactively.

2017-02-27 19:27 UTC, dcrankshaw commented on src/frontends/src/bench.cpp
> +    std::cout << label << std::endl;
Don't print the label here.

2017-02-27 19:27 UTC, dcrankshaw commented on src/frontends/src/bench.cpp
> +  std::vector<std::vector<double>> planes_vecs = cifar_data.find(0)->second;
I get a segfault at this line. I'm guessing something is wrong with loading the cifar data?

Let me know if you can't reproduce it, and I can dig into it a little more.

2017-03-03 00:51 UTC, dcrankshaw commented
@Corey-Zumar This is reviewed and ready for you to address the comments

2017-03-03 00:56 UTC, Corey-Zumar commented on bench/bench_init.py
> +
Replaced imports with the one's you've defined.

2017-03-03 00:56 UTC, Corey-Zumar commented on bench/bench_init.py
> +import requests
Removed

2017-03-03 00:56 UTC, Corey-Zumar commented on bench/bench_init.py
> +BASE_DATA_PATH = "data/"
Agreed. Changed this!

2017-03-03 00:56 UTC, Corey-Zumar commented on bench/bench_init.py
> +		model_location = BASE_DATA_PATH + SKLEARN_MODEL_FILE
Done

2017-03-03 00:56 UTC, Corey-Zumar commented on bench/bench_init.py
> +			joblib.dump(model, model_location)
Done.

2017-03-03 00:56 UTC, Corey-Zumar commented on bench/bench_init.py
> +	setup = BenchSetup("localhost", "../examples/cifar_demo")
Done. Also modified `setup_bench.sh` to accept this path as a command line argument.

2017-03-03 00:56 UTC, Corey-Zumar commented on src/frontends/src/bench.cpp
> +  std::vector<std::vector<double>> planes_vecs = cifar_data.find(0)->second;
I think the instructions I provided for running the benchmark are insufficient / unclear. For the path to the CIFAR binary data set, I'm passing a path to a file within the **binary** version of CIFAR hosted at https://www.cs.toronto.edu/~kriz/cifar.html . I'm using `data_batch_1.bin`. I should have stated this explicitly.

If you were passing a path to analogous file (`data_batch_<n>.bin`) within the binary data set and still received the seg fault, please let me know.

2017-03-03 00:56 UTC, Corey-Zumar commented on src/frontends/src/bench.cpp
> +};
Done. We can now specify a path to a JSON configuration file with the command line argument `-f ` or `--filename`. The configuration file should be formatted as follows:

```
{
   "cifar_data_path":"<path to a data_batch_<n>.bin file in the cifar binary data set>",
   "num_threads":"<number of threads>",
   "num_batches":"<number of batches>",
   "batch_size":"<batch size>",
   "batch_delay_millis":"<batch delay millis>"
}
```

2017-03-03 00:59 UTC, Corey-Zumar commented on src/frontends/src/bench.cpp
> +    std::cout << label << std::endl;
Removed this line

2017-03-03 01:00 UTC, dcrankshaw commented
jenkins test this please

2017-03-03 01:02 UTC, Corey-Zumar commented
Formatted `bench_init.py` to conform to PEP8

2017-03-03 01:07 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/47/
Test FAILed.

2017-03-03 01:25 UTC, dcrankshaw commented
jenkins test this please

2017-03-03 01:32 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/49/
Test FAILed.

2017-03-04 01:08 UTC, dcrankshaw requested changes
Looks good. A couple minor comments.

Can you add some documentation about how to run the benchmark? At a minimum, you need to specify what the dataset for the model container should be and what the dataset for the bench binary should be.

Also, I found a bug in the RPCService destructor. 


Replace [`RPCService::shutdown_service`](https://github.com/ucbrise/clipper/blob/35cb8ee0a9fe8f8ea8601d06b8cc8adcfe2fc227/src/libclipper/src/rpc_service.cpp#L130-L133) with
```cpp
void RPCService::shutdown_service(socket_t &socket) {
  size_t buf_size = 32;
  char buf[buf_size];
  socket.getsockopt(ZMQ_LAST_ENDPOINT, (void *)&buf, &buf_size);
  std::string last_endpoint = std::string(buf);
  socket.unbind(last_endpoint);
  socket.close();
 }
```

The problem is we were calling `disconnect` not `unbind`. The mess with ZMQ_LAST_ENDPOINT is because we are using wildcard addresses (http://api.zeromq.org/4-2:zmq-unbind#toc3).

2017-03-04 01:08 UTC, dcrankshaw commented on bench/setup_bench.sh
> +read cifar_path
Don't interactively ask for input, just take the location as a command line param:

```
cifar_path=$1
```

2017-03-04 01:08 UTC, dcrankshaw commented on src/frontends/src/bench.cpp
> +  std::this_thread::sleep_for(std::chrono::seconds(5));
Why are you sleeping at the end here?

2017-03-04 01:09 UTC, dcrankshaw commented
jenkins test this please

2017-03-04 01:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/52/
Test PASSed.

2017-03-06 03:38 UTC, Corey-Zumar reviewed
Added a README with a list of required files and a detailed explanation of how to run the test. I also integrated your fix for the RPC error that you identified - thanks for finding that - and addressed your other comments.

2017-03-06 03:38 UTC, Corey-Zumar commented on bench/setup_bench.sh
> +read cifar_path
Done

2017-03-06 03:38 UTC, Corey-Zumar commented on src/frontends/src/bench.cpp
> +  std::this_thread::sleep_for(std::chrono::seconds(5));
I shouldn't be. I think this was an illogical attempt to log metrics in the face of the RPC error you identified above. Removed.

2017-03-06 03:47 UTC, dcrankshaw reviewed
Looks good other than some confusion in the docs about the CIFAR python dataset.

2017-03-06 03:47 UTC, dcrankshaw commented on bench/README.md
> +This benchmark serves an SKLearn model that depends on the CIFAR10 Python dataset for training. This dataset can be obtained from [https://www.cs.toronto.edu/~kriz/cifar.html](https://www.cs.toronto.
This actually isn't true. The `cifar_utils` functions expect a CSV. You can use https://github.com/ucbrise/clipper/blob/develop/examples/tutorial/download_cifar.py to download the dataset and transform it into a CSV. If you look at the [tutorial](https://github.com/ucbrise/clipper/blob/develop/examples/tutorial/tutorial_part_one.ipynb), we first download the dataset and create the CSV, then load it to train the model.

2017-03-06 05:47 UTC, Corey-Zumar commented on bench/README.md
> +This benchmark serves an SKLearn model that depends on the CIFAR10 Python dataset for training. This dataset can be obtained from [https://www.cs.toronto.edu/~kriz/cifar.html](https://www.cs.toronto.
Thanks! Fixed this. Please take another look.

2017-03-06 21:15 UTC, dcrankshaw approved these changes

2017-03-06 21:30 UTC, dcrankshaw commented
jenkins test this please

2017-03-06 21:43 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/66/
Test PASSed.

2017-03-07 02:27 UTC, merged