[CLIPPER-102] Integrate threadpool with TaskExecutor, RPC layer
ucbrise/clipper pull request #86
Opened 2017-03-15 05:29 UTC by Corey-Zumar

2017-03-15 05:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/76/
Test PASSed.

2017-03-16 19:01 UTC, dcrankshaw requested changes
Looks good. Just make the closure capture explicit.

2017-03-16 19:01 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
> +            TaskExecutionThreadPool::submit_job([=]() {
What is this closure capturing? Can we explicitly capture only the variables we need?

2017-03-16 19:01 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
> +            TaskExecutionThreadPool::submit_job([=]() {
I think this can be: `TaskExecutionThreadPool::submit_job([this, vm, replica_id]() {`

2017-03-17 01:39 UTC, Corey-Zumar commented on src/libclipper/include/clipper/task_executor.hpp
> +            TaskExecutionThreadPool::submit_job([=]() {
Agreed, it's better to explicitly capture only the required variables. Fixed!

2017-03-17 01:48 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/79/
Test PASSed.

2017-03-17 02:38 UTC, dcrankshaw approved these changes

2017-03-17 02:38 UTC, dcrankshaw commented
LGTM

2017-03-17 02:38 UTC, merged