[CLIPPER-94][CLIPPER-133] Model-based queueing and starvation fix
ucbrise/clipper pull request #88
Opened 2017-03-18 05:34 UTC by Corey-Zumar

These two issues are addressed together because applying our starvation fixed to the previous container-based queuing solution led to invalid memory accesses by deprecated prediction scheduling code in the task executor.

2017-03-18 05:36 UTC, Corey-Zumar commented on src/frontends/src/bench.cpp
> -      std::srand(time(NULL));
Seeding at every iteration of the loop caused `rand()` to consistently produce the same value. We now seed once prior to the execution of `send_predictions`

2017-03-18 05:45 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/81/
Test PASSed.

2017-03-18 06:23 UTC, dcrankshaw requested changes
Looks good. Can we unit-test ModelQueue and any of these other pieces? It would be good to improve our test coverage before the release.

2017-03-18 06:23 UTC, dcrankshaw commented on src/libclipper/include/clipper/containers.hpp
> +using Deadline = std::chrono::time_point<std::chrono::high_resolution_clock>;
Nice. We should just use a deadline throughout. Do you feel like changing the `Query` class to have a deadline instead of a latency? You can set it by looking at the latency SLO of the associated application in `query_frontend.hpp` and figure out what the deadline should be as soon as the query is received.

2017-03-18 06:23 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
> +};
Can you add a unit test for this? I tend to mess up my comparisons and I want to be safe here.

2017-03-18 06:23 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
> +        std::chrono::microseconds(task.latency_slo_micros_);
Yeah as I mentioned above, let's set the deadline for the query once when it first arrives, then use it throughout execution.

2017-03-18 06:23 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
> +    queue_not_empty_.notify_all();
What's this notification for?

2017-03-18 06:23 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
> +      queue_not_empty_.wait(l, [this] { return queue_.size() > 0; });
Based on our discussion about task starvation, this should be a non-blocking function right? Maybe it should return a `boost::option`?

2017-03-18 06:23 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
>              // TODO: Create a new model queue if this is the first connected container
Delete the TODO if this PR addresses it

2017-03-18 06:23 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
> +                                              std::forward_as_tuple());
What are the semantics of `emplace()` here? This won't create a new entry if the key already exists?

2017-03-18 06:23 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
> +    for(int i = 0; i < 1000; i++) {
Honestly I don't think we even need to spin here. Delete the for-loop, just have an if-statement.

2017-03-18 06:23 UTC, dcrankshaw commented on src/libclipper/include/clipper/task_executor.hpp
> +      Deadline earliest_deadline = model_queue_entry->second.get_earliest_deadline();
Note that in the current implementation, `get_earliest_deadline()` is blocking. I made a comment up by the function definition to make it non-blocking but repeating it here.

2017-03-18 06:23 UTC, dcrankshaw commented
jenkins test this please

2017-03-18 06:25 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/83/
Test FAILed.

2017-03-18 06:26 UTC, dcrankshaw commented
The reason the CI format check wasn't picking things up is because I had turned it off 😃 . I just turned it back on which is why the jenkins test failed.

Run `./bin/format_code.sh` to fix it.

2017-03-22 10:04 UTC, Corey-Zumar reviewed
Addressed comments and added an additional test on `ModelQueue` for correct task ordering.

2017-03-22 10:04 UTC, Corey-Zumar commented on src/libclipper/include/clipper/task_executor.hpp
> +    for(int i = 0; i < 1000; i++) {
Done

2017-03-22 10:04 UTC, Corey-Zumar commented on src/libclipper/include/clipper/task_executor.hpp
> +                                              std::forward_as_tuple());
From [cppreference](http://en.cppreference.com/w/cpp/container/unordered_map/emplace): "(emplace) 		
Inserts a new element into the container constructed in-place with the given args if there is no element with the key in the container."

Added a comment to this effect.

2017-03-22 10:04 UTC, Corey-Zumar commented on src/libclipper/include/clipper/task_executor.hpp
>              // TODO: Create a new model queue if this is the first connected container
Done

2017-03-22 10:04 UTC, Corey-Zumar commented on src/libclipper/include/clipper/task_executor.hpp
> +      queue_not_empty_.wait(l, [this] { return queue_.size() > 0; });
Good idea. Changed so that it's non-blocking and returns `boost::optional<Deadline>`.

2017-03-22 10:04 UTC, Corey-Zumar commented on src/libclipper/include/clipper/task_executor.hpp
> +    queue_not_empty_.notify_all();
Obsolete condition variable notifier for blocking calls to `get_earliest_deadline()`. Removed.

2017-03-22 10:04 UTC, Corey-Zumar commented on src/libclipper/include/clipper/task_executor.hpp
> +      Deadline earliest_deadline = model_queue_entry->second.get_earliest_deadline();
Wrote a nonblocking version that returns a `boost::optional<Deadline>` instead

2017-03-22 10:04 UTC, Corey-Zumar commented on src/libclipper/include/clipper/task_executor.hpp
> +};
Done!

2017-03-22 10:04 UTC, Corey-Zumar commented on src/libclipper/include/clipper/containers.hpp
> +using Deadline = std::chrono::time_point<std::chrono::high_resolution_clock>;
I think we should do this in a separate PR, as it involves changes in several pieces of infrastructure that aren't immediately related to this task.

2017-03-22 10:15 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/92/
Test PASSed.

2017-03-22 10:25 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/93/
Test PASSed.

2017-03-31 20:12 UTC, dcrankshaw approved these changes
LGTM

2017-03-31 20:12 UTC, dcrankshaw commented on src/libclipper/include/clipper/containers.hpp
> +using Deadline = std::chrono::time_point<std::chrono::high_resolution_clock>;
Good point

2017-03-31 20:49 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/109/
Test PASSed.

2017-03-31 20:50 UTC, merged