Add Vagrantfile to project
ucbrise/clipper pull request #98
Opened 2017-03-30 18:59 UTC by lucasmoura

This MR request the a Vagrantfile to the project, with the aim at helping automating the creation of a development environment for new users. 

Vagrant basically will create a virtual machine running Debian stretch, install all the necessary packages and run the unit tests to see if the environment is okay.

Currently, I am using virtualbox as the virtual machine provider, but this can be updated if necessary

2017-03-30 19:00 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-03-31 05:08 UTC, dcrankshaw commented
jenkins test this please

2017-03-31 05:20 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/106/
Test PASSed.

2017-03-31 05:41 UTC, dcrankshaw requested changes
Hey this is very cool! I just have some minor edits for the documentation.

2017-03-31 05:41 UTC, dcrankshaw commented on README.md
> +done, just do the following commands to initialize vagrant.
Some minor grammar edits:

"You can use Vagrant to automatically create a development environment in a virtual machine. This is one method for using Windows for Clipper development. Before you start, you must have [Vagrant](https://www.vagrantup.com/) and [VirtualBox](https://www.virtualbox.org/wiki/VirtualBox) installed. Once you have them installed, perform the following command to initialize Vagrant."

2017-03-31 05:41 UTC, dcrankshaw commented on README.md
> +perform the following commands:
change "in your local machine" to "on your local machine"

2017-03-31 05:41 UTC, dcrankshaw commented on README.md
> +# Logs in the virtual machine
"# Log in to the virtual machine"

2017-03-31 05:41 UTC, dcrankshaw commented on README.md
> +# Enter root dir
"# Enter root Clipper directory"

2017-03-31 05:41 UTC, dcrankshaw commented on Vagrantfile
> +  config.vm.box_check_update = false
What's the purpose of this setting? Is this standard practice? I haven't used Vagrant before.

2017-03-31 13:43 UTC, lucasmoura commented on Vagrantfile
> +  config.vm.box_check_update = false
No, this is not standard practice. I was using that to just speed up the process of initializing vagrant, but I forgot to remove it :(. I will delete this line in my updated patch.

2017-03-31 13:45 UTC, lucasmoura commented
@dcrankshaw Done, I have made the requested changes :)

2017-03-31 20:09 UTC, dcrankshaw approved these changes

2017-03-31 20:09 UTC, dcrankshaw commented
jenkins test this please

2017-03-31 20:10 UTC, dcrankshaw commented
LGTM

2017-03-31 20:19 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/107/
Test PASSed.

2017-03-31 20:21 UTC, dcrankshaw commented
jenkins test this please

2017-03-31 20:35 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/108/
Test PASSed.

2017-03-31 20:37 UTC, merged